namespace Younes_Entreprise
{
    partial class CreateProductForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CreateProductForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.label1 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.catcombox = new System.Windows.Forms.ComboBox();
            this.label9 = new System.Windows.Forms.Label();
            this.fourcombox = new System.Windows.Forms.ComboBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.ajouterbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.viderbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.detailstxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ttctxtb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.prixvtxtb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.prixatxtb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.qtetxtb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.reftxtb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.desprotxtb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.modifierbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cherchbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label11 = new System.Windows.Forms.Label();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label1.Location = new System.Drawing.Point(123, 346);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(241, 25);
            this.label1.TabIndex = 48;
            this.label1.Text = "Désignation du produit :";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 25.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.Gold;
            this.label7.Location = new System.Drawing.Point(537, 36);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(583, 51);
            this.label7.TabIndex = 51;
            this.label7.Text = "Ajouter Un Nouveau Produit";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label2.Location = new System.Drawing.Point(123, 275);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(239, 25);
            this.label2.TabIndex = 53;
            this.label2.Text = "Produit Reference        :";
            // 
            // catcombox
            // 
            this.catcombox.BackColor = System.Drawing.Color.White;
            this.catcombox.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.catcombox.FormattingEnabled = true;
            this.catcombox.Location = new System.Drawing.Point(1106, 375);
            this.catcombox.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.catcombox.MaximumSize = new System.Drawing.Size(395, 0);
            this.catcombox.MinimumSize = new System.Drawing.Size(395, 0);
            this.catcombox.Name = "catcombox";
            this.catcombox.Size = new System.Drawing.Size(395, 33);
            this.catcombox.TabIndex = 10;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label9.Location = new System.Drawing.Point(862, 381);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(217, 25);
            this.label9.TabIndex = 54;
            this.label9.Text = "Nom du Categorie    :";
            // 
            // fourcombox
            // 
            this.fourcombox.BackColor = System.Drawing.Color.White;
            this.fourcombox.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.fourcombox.FormattingEnabled = true;
            this.fourcombox.Location = new System.Drawing.Point(1106, 444);
            this.fourcombox.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.fourcombox.MaximumSize = new System.Drawing.Size(395, 0);
            this.fourcombox.MinimumSize = new System.Drawing.Size(395, 0);
            this.fourcombox.Name = "fourcombox";
            this.fourcombox.Size = new System.Drawing.Size(395, 33);
            this.fourcombox.TabIndex = 11;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label3.Location = new System.Drawing.Point(862, 449);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(219, 25);
            this.label3.TabIndex = 56;
            this.label3.Text = "Nom du Fournisseur :";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label4.Location = new System.Drawing.Point(126, 413);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(239, 25);
            this.label4.TabIndex = 59;
            this.label4.Text = "Quantité                       :";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label5.Location = new System.Drawing.Point(863, 174);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(213, 25);
            this.label5.TabIndex = 61;
            this.label5.Text = "Prix D\'achat             :";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label6.Location = new System.Drawing.Point(863, 241);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(215, 25);
            this.label6.TabIndex = 63;
            this.label6.Text = "Prix de Vente           :";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label8.Location = new System.Drawing.Point(863, 309);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(214, 25);
            this.label8.TabIndex = 65;
            this.label8.Text = "TVA 20%                 :";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label10.Location = new System.Drawing.Point(730, 560);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(157, 25);
            this.label10.TabIndex = 67;
            this.label10.Text = "Autre details    ";
            // 
            // ajouterbtn
            // 
            this.ajouterbtn.AllowAnimations = true;
            this.ajouterbtn.AllowMouseEffects = true;
            this.ajouterbtn.AllowToggling = false;
            this.ajouterbtn.AnimationSpeed = 200;
            this.ajouterbtn.AutoGenerateColors = false;
            this.ajouterbtn.AutoRoundBorders = false;
            this.ajouterbtn.AutoSizeLeftIcon = true;
            this.ajouterbtn.AutoSizeRightIcon = true;
            this.ajouterbtn.BackColor = System.Drawing.Color.Transparent;
            this.ajouterbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(183)))), ((int)(((byte)(0)))));
            this.ajouterbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ajouterbtn.BackgroundImage")));
            this.ajouterbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.ButtonText = "Ajouter";
            this.ajouterbtn.ButtonTextMarginLeft = 0;
            this.ajouterbtn.ColorContrastOnClick = 45;
            this.ajouterbtn.ColorContrastOnHover = 45;
            this.ajouterbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.ajouterbtn.CustomizableEdges = borderEdges1;
            this.ajouterbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ajouterbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ajouterbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ajouterbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ajouterbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ajouterbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.ajouterbtn.ForeColor = System.Drawing.Color.White;
            this.ajouterbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ajouterbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ajouterbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ajouterbtn.IconMarginLeft = 11;
            this.ajouterbtn.IconPadding = 10;
            this.ajouterbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ajouterbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ajouterbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ajouterbtn.IconSize = 25;
            this.ajouterbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.ajouterbtn.IdleBorderRadius = 1;
            this.ajouterbtn.IdleBorderThickness = 1;
            this.ajouterbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(183)))), ((int)(((byte)(0)))));
            this.ajouterbtn.IdleIconLeftImage = null;
            this.ajouterbtn.IdleIconRightImage = null;
            this.ajouterbtn.IndicateFocus = false;
            this.ajouterbtn.Location = new System.Drawing.Point(1118, 852);
            this.ajouterbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ajouterbtn.Name = "ajouterbtn";
            this.ajouterbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ajouterbtn.OnDisabledState.BorderRadius = 1;
            this.ajouterbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.OnDisabledState.BorderThickness = 1;
            this.ajouterbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ajouterbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ajouterbtn.OnDisabledState.IconLeftImage = null;
            this.ajouterbtn.OnDisabledState.IconRightImage = null;
            this.ajouterbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.onHoverState.BorderRadius = 1;
            this.ajouterbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.onHoverState.BorderThickness = 1;
            this.ajouterbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.ajouterbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.onHoverState.IconLeftImage = null;
            this.ajouterbtn.onHoverState.IconRightImage = null;
            this.ajouterbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.ajouterbtn.OnIdleState.BorderRadius = 1;
            this.ajouterbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.OnIdleState.BorderThickness = 1;
            this.ajouterbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(183)))), ((int)(((byte)(0)))));
            this.ajouterbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ajouterbtn.OnIdleState.IconLeftImage = null;
            this.ajouterbtn.OnIdleState.IconRightImage = null;
            this.ajouterbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.OnPressedState.BorderRadius = 1;
            this.ajouterbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.OnPressedState.BorderThickness = 1;
            this.ajouterbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.ajouterbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.OnPressedState.IconLeftImage = null;
            this.ajouterbtn.OnPressedState.IconRightImage = null;
            this.ajouterbtn.Size = new System.Drawing.Size(210, 60);
            this.ajouterbtn.TabIndex = 13;
            this.ajouterbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ajouterbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ajouterbtn.TextMarginLeft = 0;
            this.ajouterbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.ajouterbtn.UseDefaultRadiusAndThickness = true;
            this.ajouterbtn.Click += new System.EventHandler(this.ajouterbtn_Click);
            // 
            // viderbtn
            // 
            this.viderbtn.AllowAnimations = true;
            this.viderbtn.AllowMouseEffects = true;
            this.viderbtn.AllowToggling = false;
            this.viderbtn.AnimationSpeed = 200;
            this.viderbtn.AutoGenerateColors = false;
            this.viderbtn.AutoRoundBorders = false;
            this.viderbtn.AutoSizeLeftIcon = true;
            this.viderbtn.AutoSizeRightIcon = true;
            this.viderbtn.BackColor = System.Drawing.Color.Transparent;
            this.viderbtn.BackColor1 = System.Drawing.Color.White;
            this.viderbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("viderbtn.BackgroundImage")));
            this.viderbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.ButtonText = "Vider";
            this.viderbtn.ButtonTextMarginLeft = 0;
            this.viderbtn.ColorContrastOnClick = 45;
            this.viderbtn.ColorContrastOnHover = 45;
            this.viderbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.viderbtn.CustomizableEdges = borderEdges2;
            this.viderbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.viderbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.viderbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.viderbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.viderbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.viderbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.viderbtn.ForeColor = System.Drawing.Color.Black;
            this.viderbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.viderbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.viderbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.viderbtn.IconMarginLeft = 11;
            this.viderbtn.IconPadding = 10;
            this.viderbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.viderbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.viderbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.viderbtn.IconSize = 25;
            this.viderbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.viderbtn.IdleBorderRadius = 1;
            this.viderbtn.IdleBorderThickness = 1;
            this.viderbtn.IdleFillColor = System.Drawing.Color.White;
            this.viderbtn.IdleIconLeftImage = null;
            this.viderbtn.IdleIconRightImage = null;
            this.viderbtn.IndicateFocus = false;
            this.viderbtn.Location = new System.Drawing.Point(570, 852);
            this.viderbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.viderbtn.Name = "viderbtn";
            this.viderbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.viderbtn.OnDisabledState.BorderRadius = 1;
            this.viderbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.OnDisabledState.BorderThickness = 1;
            this.viderbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.viderbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.viderbtn.OnDisabledState.IconLeftImage = null;
            this.viderbtn.OnDisabledState.IconRightImage = null;
            this.viderbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.viderbtn.onHoverState.BorderRadius = 1;
            this.viderbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.onHoverState.BorderThickness = 1;
            this.viderbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.viderbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.viderbtn.onHoverState.IconLeftImage = null;
            this.viderbtn.onHoverState.IconRightImage = null;
            this.viderbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.viderbtn.OnIdleState.BorderRadius = 1;
            this.viderbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.OnIdleState.BorderThickness = 1;
            this.viderbtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.viderbtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.viderbtn.OnIdleState.IconLeftImage = null;
            this.viderbtn.OnIdleState.IconRightImage = null;
            this.viderbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.viderbtn.OnPressedState.BorderRadius = 1;
            this.viderbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.OnPressedState.BorderThickness = 1;
            this.viderbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.viderbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.viderbtn.OnPressedState.IconLeftImage = null;
            this.viderbtn.OnPressedState.IconRightImage = null;
            this.viderbtn.Size = new System.Drawing.Size(210, 60);
            this.viderbtn.TabIndex = 15;
            this.viderbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.viderbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.viderbtn.TextMarginLeft = 0;
            this.viderbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.viderbtn.UseDefaultRadiusAndThickness = true;
            this.viderbtn.Click += new System.EventHandler(this.viderbtn_Click);
            // 
            // detailstxtbox
            // 
            this.detailstxtbox.AcceptsReturn = false;
            this.detailstxtbox.AcceptsTab = false;
            this.detailstxtbox.AnimationSpeed = 200;
            this.detailstxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.detailstxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.detailstxtbox.BackColor = System.Drawing.Color.Transparent;
            this.detailstxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("detailstxtbox.BackgroundImage")));
            this.detailstxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.detailstxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.detailstxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.detailstxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.detailstxtbox.BorderRadius = 1;
            this.detailstxtbox.BorderThickness = 2;
            this.detailstxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.detailstxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.detailstxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.detailstxtbox.DefaultText = "";
            this.detailstxtbox.FillColor = System.Drawing.Color.White;
            this.detailstxtbox.HideSelection = true;
            this.detailstxtbox.IconLeft = null;
            this.detailstxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.detailstxtbox.IconPadding = 0;
            this.detailstxtbox.IconRight = null;
            this.detailstxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.detailstxtbox.Lines = new string[0];
            this.detailstxtbox.Location = new System.Drawing.Point(464, 596);
            this.detailstxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.detailstxtbox.MaxLength = 32767;
            this.detailstxtbox.MinimumSize = new System.Drawing.Size(608, 197);
            this.detailstxtbox.Modified = false;
            this.detailstxtbox.Multiline = true;
            this.detailstxtbox.Name = "detailstxtbox";
            stateProperties1.BorderColor = System.Drawing.Color.Black;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.detailstxtbox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.detailstxtbox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.detailstxtbox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.detailstxtbox.OnIdleState = stateProperties4;
            this.detailstxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.detailstxtbox.PasswordChar = '\0';
            this.detailstxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.detailstxtbox.PlaceholderText = "Enter text";
            this.detailstxtbox.ReadOnly = false;
            this.detailstxtbox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.detailstxtbox.SelectedText = "";
            this.detailstxtbox.SelectionLength = 0;
            this.detailstxtbox.SelectionStart = 0;
            this.detailstxtbox.ShortcutsEnabled = true;
            this.detailstxtbox.Size = new System.Drawing.Size(692, 197);
            this.detailstxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.detailstxtbox.TabIndex = 12;
            this.detailstxtbox.TabStop = false;
            this.detailstxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.detailstxtbox.TextMarginBottom = 0;
            this.detailstxtbox.TextMarginLeft = 4;
            this.detailstxtbox.TextMarginTop = 0;
            this.detailstxtbox.TextPlaceholder = "Enter text";
            this.detailstxtbox.UseSystemPasswordChar = false;
            this.detailstxtbox.WordWrap = true;
            // 
            // ttctxtb
            // 
            this.ttctxtb.AcceptsReturn = false;
            this.ttctxtb.AcceptsTab = false;
            this.ttctxtb.AnimationSpeed = 200;
            this.ttctxtb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ttctxtb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ttctxtb.BackColor = System.Drawing.Color.Transparent;
            this.ttctxtb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ttctxtb.BackgroundImage")));
            this.ttctxtb.BorderColorActive = System.Drawing.Color.Black;
            this.ttctxtb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ttctxtb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.ttctxtb.BorderColorIdle = System.Drawing.Color.Silver;
            this.ttctxtb.BorderRadius = 1;
            this.ttctxtb.BorderThickness = 2;
            this.ttctxtb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ttctxtb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ttctxtb.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ttctxtb.DefaultText = "";
            this.ttctxtb.FillColor = System.Drawing.Color.White;
            this.ttctxtb.HideSelection = true;
            this.ttctxtb.IconLeft = null;
            this.ttctxtb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ttctxtb.IconPadding = 10;
            this.ttctxtb.IconRight = null;
            this.ttctxtb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ttctxtb.Lines = new string[0];
            this.ttctxtb.Location = new System.Drawing.Point(1106, 297);
            this.ttctxtb.Margin = new System.Windows.Forms.Padding(0);
            this.ttctxtb.MaximumSize = new System.Drawing.Size(392, 46);
            this.ttctxtb.MaxLength = 32767;
            this.ttctxtb.MinimumSize = new System.Drawing.Size(392, 46);
            this.ttctxtb.Modified = false;
            this.ttctxtb.Multiline = false;
            this.ttctxtb.Name = "ttctxtb";
            stateProperties5.BorderColor = System.Drawing.Color.Black;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ttctxtb.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ttctxtb.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ttctxtb.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ttctxtb.OnIdleState = stateProperties8;
            this.ttctxtb.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ttctxtb.PasswordChar = '\0';
            this.ttctxtb.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.ttctxtb.PlaceholderText = "Enter text";
            this.ttctxtb.ReadOnly = false;
            this.ttctxtb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ttctxtb.SelectedText = "";
            this.ttctxtb.SelectionLength = 0;
            this.ttctxtb.SelectionStart = 0;
            this.ttctxtb.ShortcutsEnabled = true;
            this.ttctxtb.Size = new System.Drawing.Size(392, 46);
            this.ttctxtb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ttctxtb.TabIndex = 9;
            this.ttctxtb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ttctxtb.TextMarginBottom = 0;
            this.ttctxtb.TextMarginLeft = 7;
            this.ttctxtb.TextMarginTop = 0;
            this.ttctxtb.TextPlaceholder = "Enter text";
            this.ttctxtb.UseSystemPasswordChar = false;
            this.ttctxtb.WordWrap = true;
            // 
            // prixvtxtb
            // 
            this.prixvtxtb.AcceptsReturn = false;
            this.prixvtxtb.AcceptsTab = false;
            this.prixvtxtb.AnimationSpeed = 200;
            this.prixvtxtb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.prixvtxtb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.prixvtxtb.BackColor = System.Drawing.Color.Transparent;
            this.prixvtxtb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("prixvtxtb.BackgroundImage")));
            this.prixvtxtb.BorderColorActive = System.Drawing.Color.Black;
            this.prixvtxtb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.prixvtxtb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.prixvtxtb.BorderColorIdle = System.Drawing.Color.Silver;
            this.prixvtxtb.BorderRadius = 1;
            this.prixvtxtb.BorderThickness = 2;
            this.prixvtxtb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.prixvtxtb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.prixvtxtb.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.prixvtxtb.DefaultText = "";
            this.prixvtxtb.FillColor = System.Drawing.Color.White;
            this.prixvtxtb.HideSelection = true;
            this.prixvtxtb.IconLeft = null;
            this.prixvtxtb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.prixvtxtb.IconPadding = 10;
            this.prixvtxtb.IconRight = null;
            this.prixvtxtb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.prixvtxtb.Lines = new string[0];
            this.prixvtxtb.Location = new System.Drawing.Point(1106, 229);
            this.prixvtxtb.Margin = new System.Windows.Forms.Padding(0);
            this.prixvtxtb.MaximumSize = new System.Drawing.Size(392, 46);
            this.prixvtxtb.MaxLength = 32767;
            this.prixvtxtb.MinimumSize = new System.Drawing.Size(392, 46);
            this.prixvtxtb.Modified = false;
            this.prixvtxtb.Multiline = false;
            this.prixvtxtb.Name = "prixvtxtb";
            stateProperties9.BorderColor = System.Drawing.Color.Black;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prixvtxtb.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.prixvtxtb.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prixvtxtb.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prixvtxtb.OnIdleState = stateProperties12;
            this.prixvtxtb.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.prixvtxtb.PasswordChar = '\0';
            this.prixvtxtb.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.prixvtxtb.PlaceholderText = "Enter text";
            this.prixvtxtb.ReadOnly = false;
            this.prixvtxtb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.prixvtxtb.SelectedText = "";
            this.prixvtxtb.SelectionLength = 0;
            this.prixvtxtb.SelectionStart = 0;
            this.prixvtxtb.ShortcutsEnabled = true;
            this.prixvtxtb.Size = new System.Drawing.Size(392, 46);
            this.prixvtxtb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.prixvtxtb.TabIndex = 8;
            this.prixvtxtb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.prixvtxtb.TextMarginBottom = 0;
            this.prixvtxtb.TextMarginLeft = 7;
            this.prixvtxtb.TextMarginTop = 0;
            this.prixvtxtb.TextPlaceholder = "Enter text";
            this.prixvtxtb.UseSystemPasswordChar = false;
            this.prixvtxtb.WordWrap = true;
            // 
            // prixatxtb
            // 
            this.prixatxtb.AcceptsReturn = false;
            this.prixatxtb.AcceptsTab = false;
            this.prixatxtb.AnimationSpeed = 200;
            this.prixatxtb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.prixatxtb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.prixatxtb.BackColor = System.Drawing.Color.Transparent;
            this.prixatxtb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("prixatxtb.BackgroundImage")));
            this.prixatxtb.BorderColorActive = System.Drawing.Color.Black;
            this.prixatxtb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.prixatxtb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.prixatxtb.BorderColorIdle = System.Drawing.Color.Silver;
            this.prixatxtb.BorderRadius = 1;
            this.prixatxtb.BorderThickness = 2;
            this.prixatxtb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.prixatxtb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.prixatxtb.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.prixatxtb.DefaultText = "";
            this.prixatxtb.FillColor = System.Drawing.Color.White;
            this.prixatxtb.HideSelection = true;
            this.prixatxtb.IconLeft = null;
            this.prixatxtb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.prixatxtb.IconPadding = 10;
            this.prixatxtb.IconRight = null;
            this.prixatxtb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.prixatxtb.Lines = new string[0];
            this.prixatxtb.Location = new System.Drawing.Point(1103, 163);
            this.prixatxtb.Margin = new System.Windows.Forms.Padding(0);
            this.prixatxtb.MaximumSize = new System.Drawing.Size(392, 46);
            this.prixatxtb.MaxLength = 32767;
            this.prixatxtb.MinimumSize = new System.Drawing.Size(395, 46);
            this.prixatxtb.Modified = false;
            this.prixatxtb.Multiline = false;
            this.prixatxtb.Name = "prixatxtb";
            stateProperties13.BorderColor = System.Drawing.Color.Black;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prixatxtb.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.prixatxtb.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prixatxtb.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prixatxtb.OnIdleState = stateProperties16;
            this.prixatxtb.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.prixatxtb.PasswordChar = '\0';
            this.prixatxtb.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.prixatxtb.PlaceholderText = "Enter text";
            this.prixatxtb.ReadOnly = false;
            this.prixatxtb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.prixatxtb.SelectedText = "";
            this.prixatxtb.SelectionLength = 0;
            this.prixatxtb.SelectionStart = 0;
            this.prixatxtb.ShortcutsEnabled = true;
            this.prixatxtb.Size = new System.Drawing.Size(395, 46);
            this.prixatxtb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.prixatxtb.TabIndex = 7;
            this.prixatxtb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.prixatxtb.TextMarginBottom = 0;
            this.prixatxtb.TextMarginLeft = 7;
            this.prixatxtb.TextMarginTop = 0;
            this.prixatxtb.TextPlaceholder = "Enter text";
            this.prixatxtb.UseSystemPasswordChar = false;
            this.prixatxtb.WordWrap = true;
            this.prixatxtb.TextChange += new System.EventHandler(this.prixatxtb_TextChange);
            // 
            // qtetxtb
            // 
            this.qtetxtb.AcceptsReturn = false;
            this.qtetxtb.AcceptsTab = false;
            this.qtetxtb.AnimationSpeed = 200;
            this.qtetxtb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.qtetxtb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.qtetxtb.BackColor = System.Drawing.Color.Transparent;
            this.qtetxtb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("qtetxtb.BackgroundImage")));
            this.qtetxtb.BorderColorActive = System.Drawing.Color.Black;
            this.qtetxtb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.qtetxtb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.qtetxtb.BorderColorIdle = System.Drawing.Color.Silver;
            this.qtetxtb.BorderRadius = 1;
            this.qtetxtb.BorderThickness = 2;
            this.qtetxtb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.qtetxtb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.qtetxtb.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.qtetxtb.DefaultText = "";
            this.qtetxtb.FillColor = System.Drawing.Color.White;
            this.qtetxtb.HideSelection = true;
            this.qtetxtb.IconLeft = null;
            this.qtetxtb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.qtetxtb.IconPadding = 10;
            this.qtetxtb.IconRight = null;
            this.qtetxtb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.qtetxtb.Lines = new string[0];
            this.qtetxtb.Location = new System.Drawing.Point(385, 399);
            this.qtetxtb.Margin = new System.Windows.Forms.Padding(0);
            this.qtetxtb.MaximumSize = new System.Drawing.Size(392, 46);
            this.qtetxtb.MaxLength = 32767;
            this.qtetxtb.MinimumSize = new System.Drawing.Size(395, 46);
            this.qtetxtb.Modified = false;
            this.qtetxtb.Multiline = false;
            this.qtetxtb.Name = "qtetxtb";
            stateProperties17.BorderColor = System.Drawing.Color.Black;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qtetxtb.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.qtetxtb.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qtetxtb.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.qtetxtb.OnIdleState = stateProperties20;
            this.qtetxtb.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.qtetxtb.PasswordChar = '\0';
            this.qtetxtb.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.qtetxtb.PlaceholderText = "Enter text";
            this.qtetxtb.ReadOnly = false;
            this.qtetxtb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.qtetxtb.SelectedText = "";
            this.qtetxtb.SelectionLength = 0;
            this.qtetxtb.SelectionStart = 0;
            this.qtetxtb.ShortcutsEnabled = true;
            this.qtetxtb.Size = new System.Drawing.Size(395, 46);
            this.qtetxtb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.qtetxtb.TabIndex = 6;
            this.qtetxtb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.qtetxtb.TextMarginBottom = 0;
            this.qtetxtb.TextMarginLeft = 7;
            this.qtetxtb.TextMarginTop = 0;
            this.qtetxtb.TextPlaceholder = "Enter text";
            this.qtetxtb.UseSystemPasswordChar = false;
            this.qtetxtb.WordWrap = true;
            // 
            // reftxtb
            // 
            this.reftxtb.AcceptsReturn = false;
            this.reftxtb.AcceptsTab = false;
            this.reftxtb.AnimationSpeed = 200;
            this.reftxtb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.reftxtb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.reftxtb.BackColor = System.Drawing.Color.Transparent;
            this.reftxtb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("reftxtb.BackgroundImage")));
            this.reftxtb.BorderColorActive = System.Drawing.Color.Black;
            this.reftxtb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reftxtb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.reftxtb.BorderColorIdle = System.Drawing.Color.Silver;
            this.reftxtb.BorderRadius = 1;
            this.reftxtb.BorderThickness = 2;
            this.reftxtb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.reftxtb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.reftxtb.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.reftxtb.DefaultText = "";
            this.reftxtb.FillColor = System.Drawing.Color.White;
            this.reftxtb.HideSelection = true;
            this.reftxtb.IconLeft = null;
            this.reftxtb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.reftxtb.IconPadding = 10;
            this.reftxtb.IconRight = null;
            this.reftxtb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.reftxtb.Lines = new string[0];
            this.reftxtb.Location = new System.Drawing.Point(385, 261);
            this.reftxtb.Margin = new System.Windows.Forms.Padding(0);
            this.reftxtb.MaximumSize = new System.Drawing.Size(392, 46);
            this.reftxtb.MaxLength = 32767;
            this.reftxtb.MinimumSize = new System.Drawing.Size(395, 46);
            this.reftxtb.Modified = false;
            this.reftxtb.Multiline = false;
            this.reftxtb.Name = "reftxtb";
            stateProperties21.BorderColor = System.Drawing.Color.Black;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.reftxtb.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.reftxtb.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.reftxtb.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.reftxtb.OnIdleState = stateProperties24;
            this.reftxtb.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.reftxtb.PasswordChar = '\0';
            this.reftxtb.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.reftxtb.PlaceholderText = "Enter text";
            this.reftxtb.ReadOnly = false;
            this.reftxtb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.reftxtb.SelectedText = "";
            this.reftxtb.SelectionLength = 0;
            this.reftxtb.SelectionStart = 0;
            this.reftxtb.ShortcutsEnabled = true;
            this.reftxtb.Size = new System.Drawing.Size(395, 46);
            this.reftxtb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.reftxtb.TabIndex = 4;
            this.reftxtb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.reftxtb.TextMarginBottom = 0;
            this.reftxtb.TextMarginLeft = 7;
            this.reftxtb.TextMarginTop = 0;
            this.reftxtb.TextPlaceholder = "Enter text";
            this.reftxtb.UseSystemPasswordChar = false;
            this.reftxtb.WordWrap = true;
            // 
            // desprotxtb
            // 
            this.desprotxtb.AcceptsReturn = false;
            this.desprotxtb.AcceptsTab = false;
            this.desprotxtb.AnimationSpeed = 200;
            this.desprotxtb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.desprotxtb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.desprotxtb.BackColor = System.Drawing.Color.Transparent;
            this.desprotxtb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("desprotxtb.BackgroundImage")));
            this.desprotxtb.BorderColorActive = System.Drawing.Color.Black;
            this.desprotxtb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.desprotxtb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.desprotxtb.BorderColorIdle = System.Drawing.Color.Silver;
            this.desprotxtb.BorderRadius = 1;
            this.desprotxtb.BorderThickness = 2;
            this.desprotxtb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.desprotxtb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.desprotxtb.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.desprotxtb.DefaultText = "";
            this.desprotxtb.FillColor = System.Drawing.Color.White;
            this.desprotxtb.HideSelection = true;
            this.desprotxtb.IconLeft = null;
            this.desprotxtb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.desprotxtb.IconPadding = 10;
            this.desprotxtb.IconRight = null;
            this.desprotxtb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.desprotxtb.Lines = new string[0];
            this.desprotxtb.Location = new System.Drawing.Point(385, 330);
            this.desprotxtb.Margin = new System.Windows.Forms.Padding(0);
            this.desprotxtb.MaximumSize = new System.Drawing.Size(392, 46);
            this.desprotxtb.MaxLength = 32767;
            this.desprotxtb.MinimumSize = new System.Drawing.Size(395, 46);
            this.desprotxtb.Modified = false;
            this.desprotxtb.Multiline = false;
            this.desprotxtb.Name = "desprotxtb";
            stateProperties25.BorderColor = System.Drawing.Color.Black;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.desprotxtb.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.desprotxtb.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.desprotxtb.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.desprotxtb.OnIdleState = stateProperties28;
            this.desprotxtb.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.desprotxtb.PasswordChar = '\0';
            this.desprotxtb.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.desprotxtb.PlaceholderText = "Enter text";
            this.desprotxtb.ReadOnly = false;
            this.desprotxtb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.desprotxtb.SelectedText = "";
            this.desprotxtb.SelectionLength = 0;
            this.desprotxtb.SelectionStart = 0;
            this.desprotxtb.ShortcutsEnabled = true;
            this.desprotxtb.Size = new System.Drawing.Size(395, 46);
            this.desprotxtb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.desprotxtb.TabIndex = 5;
            this.desprotxtb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.desprotxtb.TextMarginBottom = 0;
            this.desprotxtb.TextMarginLeft = 7;
            this.desprotxtb.TextMarginTop = 0;
            this.desprotxtb.TextPlaceholder = "Enter text";
            this.desprotxtb.UseSystemPasswordChar = false;
            this.desprotxtb.WordWrap = true;
            // 
            // modifierbtn
            // 
            this.modifierbtn.AllowAnimations = true;
            this.modifierbtn.AllowMouseEffects = true;
            this.modifierbtn.AllowToggling = false;
            this.modifierbtn.AnimationSpeed = 200;
            this.modifierbtn.AutoGenerateColors = false;
            this.modifierbtn.AutoRoundBorders = false;
            this.modifierbtn.AutoSizeLeftIcon = true;
            this.modifierbtn.AutoSizeRightIcon = true;
            this.modifierbtn.BackColor = System.Drawing.Color.Transparent;
            this.modifierbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(79)))), ((int)(((byte)(160)))));
            this.modifierbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("modifierbtn.BackgroundImage")));
            this.modifierbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.ButtonText = "Modifier";
            this.modifierbtn.ButtonTextMarginLeft = 0;
            this.modifierbtn.ColorContrastOnClick = 45;
            this.modifierbtn.ColorContrastOnHover = 45;
            this.modifierbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.modifierbtn.CustomizableEdges = borderEdges3;
            this.modifierbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.modifierbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modifierbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modifierbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modifierbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.modifierbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.modifierbtn.ForeColor = System.Drawing.Color.White;
            this.modifierbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.modifierbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.modifierbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.modifierbtn.IconMarginLeft = 11;
            this.modifierbtn.IconPadding = 10;
            this.modifierbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.modifierbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.modifierbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.modifierbtn.IconSize = 25;
            this.modifierbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.modifierbtn.IdleBorderRadius = 1;
            this.modifierbtn.IdleBorderThickness = 1;
            this.modifierbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(79)))), ((int)(((byte)(160)))));
            this.modifierbtn.IdleIconLeftImage = null;
            this.modifierbtn.IdleIconRightImage = null;
            this.modifierbtn.IndicateFocus = false;
            this.modifierbtn.Location = new System.Drawing.Point(844, 852);
            this.modifierbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.modifierbtn.Name = "modifierbtn";
            this.modifierbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modifierbtn.OnDisabledState.BorderRadius = 1;
            this.modifierbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.OnDisabledState.BorderThickness = 1;
            this.modifierbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modifierbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modifierbtn.OnDisabledState.IconLeftImage = null;
            this.modifierbtn.OnDisabledState.IconRightImage = null;
            this.modifierbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.modifierbtn.onHoverState.BorderRadius = 1;
            this.modifierbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.onHoverState.BorderThickness = 1;
            this.modifierbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.modifierbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.modifierbtn.onHoverState.IconLeftImage = null;
            this.modifierbtn.onHoverState.IconRightImage = null;
            this.modifierbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.modifierbtn.OnIdleState.BorderRadius = 1;
            this.modifierbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.OnIdleState.BorderThickness = 1;
            this.modifierbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(79)))), ((int)(((byte)(160)))));
            this.modifierbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.modifierbtn.OnIdleState.IconLeftImage = null;
            this.modifierbtn.OnIdleState.IconRightImage = null;
            this.modifierbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.modifierbtn.OnPressedState.BorderRadius = 1;
            this.modifierbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.OnPressedState.BorderThickness = 1;
            this.modifierbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.modifierbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.modifierbtn.OnPressedState.IconLeftImage = null;
            this.modifierbtn.OnPressedState.IconRightImage = null;
            this.modifierbtn.Size = new System.Drawing.Size(210, 60);
            this.modifierbtn.TabIndex = 14;
            this.modifierbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.modifierbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.modifierbtn.TextMarginLeft = 0;
            this.modifierbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.modifierbtn.UseDefaultRadiusAndThickness = true;
            this.modifierbtn.Click += new System.EventHandler(this.modifierbtn_Click);
            // 
            // cherchbtn
            // 
            this.cherchbtn.AllowAnimations = true;
            this.cherchbtn.AllowMouseEffects = true;
            this.cherchbtn.AllowToggling = false;
            this.cherchbtn.AnimationSpeed = 200;
            this.cherchbtn.AutoGenerateColors = false;
            this.cherchbtn.AutoRoundBorders = false;
            this.cherchbtn.AutoSizeLeftIcon = true;
            this.cherchbtn.AutoSizeRightIcon = true;
            this.cherchbtn.BackColor = System.Drawing.Color.Transparent;
            this.cherchbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(45)))));
            this.cherchbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cherchbtn.BackgroundImage")));
            this.cherchbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.ButtonText = "Recherche";
            this.cherchbtn.ButtonTextMarginLeft = 0;
            this.cherchbtn.ColorContrastOnClick = 45;
            this.cherchbtn.ColorContrastOnHover = 45;
            this.cherchbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.cherchbtn.CustomizableEdges = borderEdges4;
            this.cherchbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.cherchbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cherchbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cherchbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cherchbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.cherchbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.cherchbtn.ForeColor = System.Drawing.Color.White;
            this.cherchbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cherchbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.cherchbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.cherchbtn.IconMarginLeft = 11;
            this.cherchbtn.IconPadding = 10;
            this.cherchbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cherchbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.cherchbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.cherchbtn.IconSize = 25;
            this.cherchbtn.IdleBorderColor = System.Drawing.Color.White;
            this.cherchbtn.IdleBorderRadius = 1;
            this.cherchbtn.IdleBorderThickness = 1;
            this.cherchbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(45)))));
            this.cherchbtn.IdleIconLeftImage = null;
            this.cherchbtn.IdleIconRightImage = null;
            this.cherchbtn.IndicateFocus = false;
            this.cherchbtn.Location = new System.Drawing.Point(296, 852);
            this.cherchbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.cherchbtn.Name = "cherchbtn";
            this.cherchbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cherchbtn.OnDisabledState.BorderRadius = 1;
            this.cherchbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.OnDisabledState.BorderThickness = 1;
            this.cherchbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cherchbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cherchbtn.OnDisabledState.IconLeftImage = null;
            this.cherchbtn.OnDisabledState.IconRightImage = null;
            this.cherchbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.cherchbtn.onHoverState.BorderRadius = 1;
            this.cherchbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.onHoverState.BorderThickness = 1;
            this.cherchbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cherchbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.cherchbtn.onHoverState.IconLeftImage = null;
            this.cherchbtn.onHoverState.IconRightImage = null;
            this.cherchbtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.cherchbtn.OnIdleState.BorderRadius = 1;
            this.cherchbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.OnIdleState.BorderThickness = 1;
            this.cherchbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(45)))));
            this.cherchbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.cherchbtn.OnIdleState.IconLeftImage = null;
            this.cherchbtn.OnIdleState.IconRightImage = null;
            this.cherchbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.cherchbtn.OnPressedState.BorderRadius = 1;
            this.cherchbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.OnPressedState.BorderThickness = 1;
            this.cherchbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cherchbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.cherchbtn.OnPressedState.IconLeftImage = null;
            this.cherchbtn.OnPressedState.IconRightImage = null;
            this.cherchbtn.Size = new System.Drawing.Size(210, 60);
            this.cherchbtn.TabIndex = 16;
            this.cherchbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.cherchbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.cherchbtn.TextMarginLeft = 0;
            this.cherchbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.cherchbtn.UseDefaultRadiusAndThickness = true;
            this.cherchbtn.Click += new System.EventHandler(this.cherchbtn_Click);
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label11.Location = new System.Drawing.Point(123, 203);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(240, 25);
            this.label11.TabIndex = 69;
            this.label11.Text = "Produit ID                     :";
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.Black;
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox1.BorderRadius = 1;
            this.bunifuTextBox1.BorderThickness = 2;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            this.bunifuTextBox1.Location = new System.Drawing.Point(385, 192);
            this.bunifuTextBox1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuTextBox1.MaximumSize = new System.Drawing.Size(392, 46);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(395, 46);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties29.BorderColor = System.Drawing.Color.Black;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties32;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.bunifuTextBox1.PlaceholderText = "Enter text";
            this.bunifuTextBox1.ReadOnly = false;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(395, 46);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 3;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 7;
            this.bunifuTextBox1.TextMarginTop = 0;
            this.bunifuTextBox1.TextPlaceholder = "Enter text";
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // CreateProductForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.AutoScroll = true;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(50)))), ((int)(((byte)(59)))));
            this.ClientSize = new System.Drawing.Size(1605, 945);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.bunifuTextBox1);
            this.Controls.Add(this.cherchbtn);
            this.Controls.Add(this.modifierbtn);
            this.Controls.Add(this.ajouterbtn);
            this.Controls.Add(this.viderbtn);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.detailstxtbox);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.ttctxtb);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.prixvtxtb);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.prixatxtb);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.qtetxtb);
            this.Controls.Add(this.fourcombox);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.catcombox);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.reftxtb);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.desprotxtb);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.MaximumSize = new System.Drawing.Size(1605, 945);
            this.Name = "CreateProductForm";
            this.Text = "Ajouter Un Produit";
            this.Load += new System.EventHandler(this.CreateProductForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox desprotxtb;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox reftxtb;
        private System.Windows.Forms.ComboBox catcombox;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.ComboBox fourcombox;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox qtetxtb;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox prixatxtb;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox prixvtxtb;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuTextBox ttctxtb;
        private System.Windows.Forms.Label label10;
        private Bunifu.UI.WinForms.BunifuTextBox detailstxtbox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ajouterbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton viderbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton modifierbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton cherchbtn;
        private System.Windows.Forms.Label label11;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
    }
}