namespace Younes_Entreprise
{
    partial class CreateEmplyeeForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CreateEmplyeeForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.label10 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.typecombox = new System.Windows.Forms.ComboBox();
            this.label9 = new System.Windows.Forms.Label();
            this.detailstxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.salairetxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ajouterbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.emailtxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.adressetxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.phonetxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nomtxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cintxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.modifierbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.viderbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cherchbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SuspendLayout();
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label10.Location = new System.Drawing.Point(424, 166);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(241, 25);
            this.label10.TabIndex = 71;
            this.label10.Text = "Type D\'employé           :";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 25.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.Gold;
            this.label7.Location = new System.Drawing.Point(510, 29);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(615, 51);
            this.label7.TabIndex = 67;
            this.label7.Text = "Ajouter Un Nouveau Employé";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label8.Location = new System.Drawing.Point(424, 525);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(242, 25);
            this.label8.TabIndex = 66;
            this.label8.Text = "Salaire D\'employé        :";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label5.Location = new System.Drawing.Point(424, 467);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(239, 25);
            this.label5.TabIndex = 64;
            this.label5.Text = "Email D\'employé          :";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label6.Location = new System.Drawing.Point(424, 405);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(242, 25);
            this.label6.TabIndex = 62;
            this.label6.Text = "Adresse D\'employé      :";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label3.Location = new System.Drawing.Point(424, 339);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(241, 25);
            this.label3.TabIndex = 60;
            this.label3.Text = "Telephone D\'employé  :";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label2.Location = new System.Drawing.Point(424, 280);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(242, 25);
            this.label2.TabIndex = 56;
            this.label2.Text = "Nom  D\'employé           :";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label1.Location = new System.Drawing.Point(424, 220);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(243, 25);
            this.label1.TabIndex = 54;
            this.label1.Text = "ID D\'employé                :";
            // 
            // typecombox
            // 
            this.typecombox.BackColor = System.Drawing.Color.White;
            this.typecombox.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.typecombox.FormattingEnabled = true;
            this.typecombox.Items.AddRange(new object[] {
            "Gérant",
            "Co Gérant",
            "technicien auto",
            "technicien pneumatique",
            "assistante accueil",
            "Autre"});
            this.typecombox.Location = new System.Drawing.Point(701, 163);
            this.typecombox.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.typecombox.MinimumSize = new System.Drawing.Size(448, 0);
            this.typecombox.Name = "typecombox";
            this.typecombox.Size = new System.Drawing.Size(448, 28);
            this.typecombox.TabIndex = 1;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label9.Location = new System.Drawing.Point(424, 588);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(242, 25);
            this.label9.TabIndex = 76;
            this.label9.Text = "Autre details                 :";
            // 
            // detailstxtbox
            // 
            this.detailstxtbox.AcceptsReturn = false;
            this.detailstxtbox.AcceptsTab = false;
            this.detailstxtbox.AnimationSpeed = 200;
            this.detailstxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.detailstxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.detailstxtbox.BackColor = System.Drawing.Color.Transparent;
            this.detailstxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("detailstxtbox.BackgroundImage")));
            this.detailstxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.detailstxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.detailstxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.detailstxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.detailstxtbox.BorderRadius = 1;
            this.detailstxtbox.BorderThickness = 2;
            this.detailstxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.detailstxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.detailstxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.detailstxtbox.DefaultText = "";
            this.detailstxtbox.FillColor = System.Drawing.Color.White;
            this.detailstxtbox.HideSelection = true;
            this.detailstxtbox.IconLeft = null;
            this.detailstxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.detailstxtbox.IconPadding = 0;
            this.detailstxtbox.IconRight = null;
            this.detailstxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.detailstxtbox.Lines = new string[0];
            this.detailstxtbox.Location = new System.Drawing.Point(701, 581);
            this.detailstxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.detailstxtbox.MaxLength = 32767;
            this.detailstxtbox.MinimumSize = new System.Drawing.Size(448, 176);
            this.detailstxtbox.Modified = false;
            this.detailstxtbox.Multiline = true;
            this.detailstxtbox.Name = "detailstxtbox";
            stateProperties1.BorderColor = System.Drawing.Color.Black;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.detailstxtbox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.detailstxtbox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.detailstxtbox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.detailstxtbox.OnIdleState = stateProperties4;
            this.detailstxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.detailstxtbox.PasswordChar = '\0';
            this.detailstxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.detailstxtbox.PlaceholderText = "Enter text";
            this.detailstxtbox.ReadOnly = false;
            this.detailstxtbox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.detailstxtbox.SelectedText = "";
            this.detailstxtbox.SelectionLength = 0;
            this.detailstxtbox.SelectionStart = 0;
            this.detailstxtbox.ShortcutsEnabled = true;
            this.detailstxtbox.Size = new System.Drawing.Size(448, 176);
            this.detailstxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.detailstxtbox.TabIndex = 8;
            this.detailstxtbox.TabStop = false;
            this.detailstxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.detailstxtbox.TextMarginBottom = 0;
            this.detailstxtbox.TextMarginLeft = 4;
            this.detailstxtbox.TextMarginTop = 0;
            this.detailstxtbox.TextPlaceholder = "Enter text";
            this.detailstxtbox.UseSystemPasswordChar = false;
            this.detailstxtbox.WordWrap = true;
            // 
            // salairetxtbox
            // 
            this.salairetxtbox.AcceptsReturn = false;
            this.salairetxtbox.AcceptsTab = false;
            this.salairetxtbox.AnimationSpeed = 200;
            this.salairetxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.salairetxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.salairetxtbox.BackColor = System.Drawing.Color.Transparent;
            this.salairetxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("salairetxtbox.BackgroundImage")));
            this.salairetxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.salairetxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.salairetxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.salairetxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.salairetxtbox.BorderRadius = 1;
            this.salairetxtbox.BorderThickness = 2;
            this.salairetxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.salairetxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.salairetxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.salairetxtbox.DefaultText = "";
            this.salairetxtbox.FillColor = System.Drawing.Color.White;
            this.salairetxtbox.HideSelection = true;
            this.salairetxtbox.IconLeft = null;
            this.salairetxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.salairetxtbox.IconPadding = 10;
            this.salairetxtbox.IconRight = null;
            this.salairetxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.salairetxtbox.Lines = new string[0];
            this.salairetxtbox.Location = new System.Drawing.Point(701, 517);
            this.salairetxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.salairetxtbox.MaxLength = 32767;
            this.salairetxtbox.MinimumSize = new System.Drawing.Size(448, 46);
            this.salairetxtbox.Modified = false;
            this.salairetxtbox.Multiline = false;
            this.salairetxtbox.Name = "salairetxtbox";
            stateProperties5.BorderColor = System.Drawing.Color.Black;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.salairetxtbox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.salairetxtbox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.salairetxtbox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.salairetxtbox.OnIdleState = stateProperties8;
            this.salairetxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.salairetxtbox.PasswordChar = '\0';
            this.salairetxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.salairetxtbox.PlaceholderText = "Enter text";
            this.salairetxtbox.ReadOnly = false;
            this.salairetxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.salairetxtbox.SelectedText = "";
            this.salairetxtbox.SelectionLength = 0;
            this.salairetxtbox.SelectionStart = 0;
            this.salairetxtbox.ShortcutsEnabled = true;
            this.salairetxtbox.Size = new System.Drawing.Size(448, 46);
            this.salairetxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.salairetxtbox.TabIndex = 7;
            this.salairetxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.salairetxtbox.TextMarginBottom = 0;
            this.salairetxtbox.TextMarginLeft = 7;
            this.salairetxtbox.TextMarginTop = 0;
            this.salairetxtbox.TextPlaceholder = "Enter text";
            this.salairetxtbox.UseSystemPasswordChar = false;
            this.salairetxtbox.WordWrap = true;
            // 
            // ajouterbtn
            // 
            this.ajouterbtn.AllowAnimations = true;
            this.ajouterbtn.AllowMouseEffects = true;
            this.ajouterbtn.AllowToggling = false;
            this.ajouterbtn.AnimationSpeed = 200;
            this.ajouterbtn.AutoGenerateColors = false;
            this.ajouterbtn.AutoRoundBorders = false;
            this.ajouterbtn.AutoSizeLeftIcon = true;
            this.ajouterbtn.AutoSizeRightIcon = true;
            this.ajouterbtn.BackColor = System.Drawing.Color.Transparent;
            this.ajouterbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(183)))), ((int)(((byte)(0)))));
            this.ajouterbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ajouterbtn.BackgroundImage")));
            this.ajouterbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.ButtonText = "Ajouter";
            this.ajouterbtn.ButtonTextMarginLeft = 0;
            this.ajouterbtn.ColorContrastOnClick = 45;
            this.ajouterbtn.ColorContrastOnHover = 45;
            this.ajouterbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.ajouterbtn.CustomizableEdges = borderEdges1;
            this.ajouterbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ajouterbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ajouterbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ajouterbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ajouterbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ajouterbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.ajouterbtn.ForeColor = System.Drawing.Color.White;
            this.ajouterbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ajouterbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ajouterbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ajouterbtn.IconMarginLeft = 11;
            this.ajouterbtn.IconPadding = 10;
            this.ajouterbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ajouterbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ajouterbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ajouterbtn.IconSize = 25;
            this.ajouterbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.ajouterbtn.IdleBorderRadius = 1;
            this.ajouterbtn.IdleBorderThickness = 1;
            this.ajouterbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(183)))), ((int)(((byte)(0)))));
            this.ajouterbtn.IdleIconLeftImage = null;
            this.ajouterbtn.IdleIconRightImage = null;
            this.ajouterbtn.IndicateFocus = false;
            this.ajouterbtn.Location = new System.Drawing.Point(1110, 833);
            this.ajouterbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ajouterbtn.Name = "ajouterbtn";
            this.ajouterbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ajouterbtn.OnDisabledState.BorderRadius = 1;
            this.ajouterbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.OnDisabledState.BorderThickness = 1;
            this.ajouterbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ajouterbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ajouterbtn.OnDisabledState.IconLeftImage = null;
            this.ajouterbtn.OnDisabledState.IconRightImage = null;
            this.ajouterbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.onHoverState.BorderRadius = 1;
            this.ajouterbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.onHoverState.BorderThickness = 1;
            this.ajouterbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.ajouterbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.onHoverState.IconLeftImage = null;
            this.ajouterbtn.onHoverState.IconRightImage = null;
            this.ajouterbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.ajouterbtn.OnIdleState.BorderRadius = 1;
            this.ajouterbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.OnIdleState.BorderThickness = 1;
            this.ajouterbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(183)))), ((int)(((byte)(0)))));
            this.ajouterbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ajouterbtn.OnIdleState.IconLeftImage = null;
            this.ajouterbtn.OnIdleState.IconRightImage = null;
            this.ajouterbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.OnPressedState.BorderRadius = 1;
            this.ajouterbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.OnPressedState.BorderThickness = 1;
            this.ajouterbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.ajouterbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.OnPressedState.IconLeftImage = null;
            this.ajouterbtn.OnPressedState.IconRightImage = null;
            this.ajouterbtn.Size = new System.Drawing.Size(210, 60);
            this.ajouterbtn.TabIndex = 9;
            this.ajouterbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ajouterbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ajouterbtn.TextMarginLeft = 0;
            this.ajouterbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.ajouterbtn.UseDefaultRadiusAndThickness = true;
            this.ajouterbtn.Click += new System.EventHandler(this.ajouterbtn_Click);
            // 
            // emailtxtbox
            // 
            this.emailtxtbox.AcceptsReturn = false;
            this.emailtxtbox.AcceptsTab = false;
            this.emailtxtbox.AnimationSpeed = 200;
            this.emailtxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailtxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailtxtbox.BackColor = System.Drawing.Color.Transparent;
            this.emailtxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailtxtbox.BackgroundImage")));
            this.emailtxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.emailtxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.emailtxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.emailtxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.emailtxtbox.BorderRadius = 1;
            this.emailtxtbox.BorderThickness = 2;
            this.emailtxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailtxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailtxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.emailtxtbox.DefaultText = "";
            this.emailtxtbox.FillColor = System.Drawing.Color.White;
            this.emailtxtbox.HideSelection = true;
            this.emailtxtbox.IconLeft = null;
            this.emailtxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailtxtbox.IconPadding = 10;
            this.emailtxtbox.IconRight = null;
            this.emailtxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailtxtbox.Lines = new string[0];
            this.emailtxtbox.Location = new System.Drawing.Point(701, 454);
            this.emailtxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.emailtxtbox.MaxLength = 32767;
            this.emailtxtbox.MinimumSize = new System.Drawing.Size(448, 46);
            this.emailtxtbox.Modified = false;
            this.emailtxtbox.Multiline = false;
            this.emailtxtbox.Name = "emailtxtbox";
            stateProperties9.BorderColor = System.Drawing.Color.Black;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailtxtbox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailtxtbox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailtxtbox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailtxtbox.OnIdleState = stateProperties12;
            this.emailtxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.emailtxtbox.PasswordChar = '\0';
            this.emailtxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.emailtxtbox.PlaceholderText = "Enter text";
            this.emailtxtbox.ReadOnly = false;
            this.emailtxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailtxtbox.SelectedText = "";
            this.emailtxtbox.SelectionLength = 0;
            this.emailtxtbox.SelectionStart = 0;
            this.emailtxtbox.ShortcutsEnabled = true;
            this.emailtxtbox.Size = new System.Drawing.Size(448, 46);
            this.emailtxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailtxtbox.TabIndex = 6;
            this.emailtxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.emailtxtbox.TextMarginBottom = 0;
            this.emailtxtbox.TextMarginLeft = 7;
            this.emailtxtbox.TextMarginTop = 0;
            this.emailtxtbox.TextPlaceholder = "Enter text";
            this.emailtxtbox.UseSystemPasswordChar = false;
            this.emailtxtbox.WordWrap = true;
            // 
            // adressetxtbox
            // 
            this.adressetxtbox.AcceptsReturn = false;
            this.adressetxtbox.AcceptsTab = false;
            this.adressetxtbox.AnimationSpeed = 200;
            this.adressetxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.adressetxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.adressetxtbox.BackColor = System.Drawing.Color.Transparent;
            this.adressetxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("adressetxtbox.BackgroundImage")));
            this.adressetxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.adressetxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.adressetxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.adressetxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.adressetxtbox.BorderRadius = 1;
            this.adressetxtbox.BorderThickness = 2;
            this.adressetxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.adressetxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.adressetxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.adressetxtbox.DefaultText = "";
            this.adressetxtbox.FillColor = System.Drawing.Color.White;
            this.adressetxtbox.HideSelection = true;
            this.adressetxtbox.IconLeft = null;
            this.adressetxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.adressetxtbox.IconPadding = 10;
            this.adressetxtbox.IconRight = null;
            this.adressetxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.adressetxtbox.Lines = new string[0];
            this.adressetxtbox.Location = new System.Drawing.Point(701, 392);
            this.adressetxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.adressetxtbox.MaxLength = 32767;
            this.adressetxtbox.MinimumSize = new System.Drawing.Size(448, 46);
            this.adressetxtbox.Modified = false;
            this.adressetxtbox.Multiline = false;
            this.adressetxtbox.Name = "adressetxtbox";
            stateProperties13.BorderColor = System.Drawing.Color.Black;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adressetxtbox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.adressetxtbox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adressetxtbox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adressetxtbox.OnIdleState = stateProperties16;
            this.adressetxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.adressetxtbox.PasswordChar = '\0';
            this.adressetxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.adressetxtbox.PlaceholderText = "Enter text";
            this.adressetxtbox.ReadOnly = false;
            this.adressetxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.adressetxtbox.SelectedText = "";
            this.adressetxtbox.SelectionLength = 0;
            this.adressetxtbox.SelectionStart = 0;
            this.adressetxtbox.ShortcutsEnabled = true;
            this.adressetxtbox.Size = new System.Drawing.Size(448, 46);
            this.adressetxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.adressetxtbox.TabIndex = 5;
            this.adressetxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.adressetxtbox.TextMarginBottom = 0;
            this.adressetxtbox.TextMarginLeft = 7;
            this.adressetxtbox.TextMarginTop = 0;
            this.adressetxtbox.TextPlaceholder = "Enter text";
            this.adressetxtbox.UseSystemPasswordChar = false;
            this.adressetxtbox.WordWrap = true;
            // 
            // phonetxtbox
            // 
            this.phonetxtbox.AcceptsReturn = false;
            this.phonetxtbox.AcceptsTab = false;
            this.phonetxtbox.AnimationSpeed = 200;
            this.phonetxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phonetxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phonetxtbox.BackColor = System.Drawing.Color.Transparent;
            this.phonetxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phonetxtbox.BackgroundImage")));
            this.phonetxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.phonetxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phonetxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.phonetxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.phonetxtbox.BorderRadius = 1;
            this.phonetxtbox.BorderThickness = 2;
            this.phonetxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phonetxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phonetxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.phonetxtbox.DefaultText = "";
            this.phonetxtbox.FillColor = System.Drawing.Color.White;
            this.phonetxtbox.HideSelection = true;
            this.phonetxtbox.IconLeft = null;
            this.phonetxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonetxtbox.IconPadding = 10;
            this.phonetxtbox.IconRight = null;
            this.phonetxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonetxtbox.Lines = new string[0];
            this.phonetxtbox.Location = new System.Drawing.Point(701, 330);
            this.phonetxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.phonetxtbox.MaxLength = 32767;
            this.phonetxtbox.MinimumSize = new System.Drawing.Size(448, 46);
            this.phonetxtbox.Modified = false;
            this.phonetxtbox.Multiline = false;
            this.phonetxtbox.Name = "phonetxtbox";
            stateProperties17.BorderColor = System.Drawing.Color.Black;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonetxtbox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phonetxtbox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonetxtbox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonetxtbox.OnIdleState = stateProperties20;
            this.phonetxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.phonetxtbox.PasswordChar = '\0';
            this.phonetxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.phonetxtbox.PlaceholderText = "Enter text";
            this.phonetxtbox.ReadOnly = false;
            this.phonetxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phonetxtbox.SelectedText = "";
            this.phonetxtbox.SelectionLength = 0;
            this.phonetxtbox.SelectionStart = 0;
            this.phonetxtbox.ShortcutsEnabled = true;
            this.phonetxtbox.Size = new System.Drawing.Size(448, 46);
            this.phonetxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phonetxtbox.TabIndex = 4;
            this.phonetxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phonetxtbox.TextMarginBottom = 0;
            this.phonetxtbox.TextMarginLeft = 7;
            this.phonetxtbox.TextMarginTop = 0;
            this.phonetxtbox.TextPlaceholder = "Enter text";
            this.phonetxtbox.UseSystemPasswordChar = false;
            this.phonetxtbox.WordWrap = true;
            // 
            // nomtxtbox
            // 
            this.nomtxtbox.AcceptsReturn = false;
            this.nomtxtbox.AcceptsTab = false;
            this.nomtxtbox.AnimationSpeed = 200;
            this.nomtxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nomtxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nomtxtbox.BackColor = System.Drawing.Color.Transparent;
            this.nomtxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nomtxtbox.BackgroundImage")));
            this.nomtxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.nomtxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nomtxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.nomtxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.nomtxtbox.BorderRadius = 1;
            this.nomtxtbox.BorderThickness = 2;
            this.nomtxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nomtxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nomtxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nomtxtbox.DefaultText = "";
            this.nomtxtbox.FillColor = System.Drawing.Color.White;
            this.nomtxtbox.HideSelection = true;
            this.nomtxtbox.IconLeft = null;
            this.nomtxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomtxtbox.IconPadding = 10;
            this.nomtxtbox.IconRight = null;
            this.nomtxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomtxtbox.Lines = new string[0];
            this.nomtxtbox.Location = new System.Drawing.Point(701, 269);
            this.nomtxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.nomtxtbox.MaxLength = 32767;
            this.nomtxtbox.MinimumSize = new System.Drawing.Size(448, 46);
            this.nomtxtbox.Modified = false;
            this.nomtxtbox.Multiline = false;
            this.nomtxtbox.Name = "nomtxtbox";
            stateProperties21.BorderColor = System.Drawing.Color.Black;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomtxtbox.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nomtxtbox.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomtxtbox.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomtxtbox.OnIdleState = stateProperties24;
            this.nomtxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.nomtxtbox.PasswordChar = '\0';
            this.nomtxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.nomtxtbox.PlaceholderText = "Enter text";
            this.nomtxtbox.ReadOnly = false;
            this.nomtxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nomtxtbox.SelectedText = "";
            this.nomtxtbox.SelectionLength = 0;
            this.nomtxtbox.SelectionStart = 0;
            this.nomtxtbox.ShortcutsEnabled = true;
            this.nomtxtbox.Size = new System.Drawing.Size(448, 46);
            this.nomtxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nomtxtbox.TabIndex = 3;
            this.nomtxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nomtxtbox.TextMarginBottom = 0;
            this.nomtxtbox.TextMarginLeft = 7;
            this.nomtxtbox.TextMarginTop = 0;
            this.nomtxtbox.TextPlaceholder = "Enter text";
            this.nomtxtbox.UseSystemPasswordChar = false;
            this.nomtxtbox.WordWrap = true;
            // 
            // cintxtbox
            // 
            this.cintxtbox.AcceptsReturn = false;
            this.cintxtbox.AcceptsTab = false;
            this.cintxtbox.AnimationSpeed = 200;
            this.cintxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cintxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cintxtbox.BackColor = System.Drawing.Color.Transparent;
            this.cintxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cintxtbox.BackgroundImage")));
            this.cintxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.cintxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cintxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cintxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.cintxtbox.BorderRadius = 1;
            this.cintxtbox.BorderThickness = 2;
            this.cintxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cintxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cintxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cintxtbox.DefaultText = "";
            this.cintxtbox.FillColor = System.Drawing.Color.White;
            this.cintxtbox.HideSelection = true;
            this.cintxtbox.IconLeft = null;
            this.cintxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cintxtbox.IconPadding = 10;
            this.cintxtbox.IconRight = null;
            this.cintxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cintxtbox.Lines = new string[0];
            this.cintxtbox.Location = new System.Drawing.Point(701, 208);
            this.cintxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.cintxtbox.MaxLength = 32767;
            this.cintxtbox.MinimumSize = new System.Drawing.Size(448, 46);
            this.cintxtbox.Modified = false;
            this.cintxtbox.Multiline = false;
            this.cintxtbox.Name = "cintxtbox";
            stateProperties25.BorderColor = System.Drawing.Color.Black;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cintxtbox.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cintxtbox.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cintxtbox.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cintxtbox.OnIdleState = stateProperties28;
            this.cintxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.cintxtbox.PasswordChar = '\0';
            this.cintxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.cintxtbox.PlaceholderText = "Enter text";
            this.cintxtbox.ReadOnly = false;
            this.cintxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cintxtbox.SelectedText = "";
            this.cintxtbox.SelectionLength = 0;
            this.cintxtbox.SelectionStart = 0;
            this.cintxtbox.ShortcutsEnabled = true;
            this.cintxtbox.Size = new System.Drawing.Size(448, 46);
            this.cintxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cintxtbox.TabIndex = 2;
            this.cintxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cintxtbox.TextMarginBottom = 0;
            this.cintxtbox.TextMarginLeft = 7;
            this.cintxtbox.TextMarginTop = 0;
            this.cintxtbox.TextPlaceholder = "Enter text";
            this.cintxtbox.UseSystemPasswordChar = false;
            this.cintxtbox.WordWrap = true;
            // 
            // modifierbtn
            // 
            this.modifierbtn.AllowAnimations = true;
            this.modifierbtn.AllowMouseEffects = true;
            this.modifierbtn.AllowToggling = false;
            this.modifierbtn.AnimationSpeed = 200;
            this.modifierbtn.AutoGenerateColors = false;
            this.modifierbtn.AutoRoundBorders = false;
            this.modifierbtn.AutoSizeLeftIcon = true;
            this.modifierbtn.AutoSizeRightIcon = true;
            this.modifierbtn.BackColor = System.Drawing.Color.Transparent;
            this.modifierbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(79)))), ((int)(((byte)(160)))));
            this.modifierbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("modifierbtn.BackgroundImage")));
            this.modifierbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.ButtonText = "Modifier";
            this.modifierbtn.ButtonTextMarginLeft = 0;
            this.modifierbtn.ColorContrastOnClick = 45;
            this.modifierbtn.ColorContrastOnHover = 45;
            this.modifierbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.modifierbtn.CustomizableEdges = borderEdges2;
            this.modifierbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.modifierbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modifierbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modifierbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modifierbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.modifierbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.modifierbtn.ForeColor = System.Drawing.Color.White;
            this.modifierbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.modifierbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.modifierbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.modifierbtn.IconMarginLeft = 11;
            this.modifierbtn.IconPadding = 10;
            this.modifierbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.modifierbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.modifierbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.modifierbtn.IconSize = 25;
            this.modifierbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.modifierbtn.IdleBorderRadius = 1;
            this.modifierbtn.IdleBorderThickness = 1;
            this.modifierbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(79)))), ((int)(((byte)(160)))));
            this.modifierbtn.IdleIconLeftImage = null;
            this.modifierbtn.IdleIconRightImage = null;
            this.modifierbtn.IndicateFocus = false;
            this.modifierbtn.Location = new System.Drawing.Point(846, 833);
            this.modifierbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.modifierbtn.Name = "modifierbtn";
            this.modifierbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modifierbtn.OnDisabledState.BorderRadius = 1;
            this.modifierbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.OnDisabledState.BorderThickness = 1;
            this.modifierbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modifierbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modifierbtn.OnDisabledState.IconLeftImage = null;
            this.modifierbtn.OnDisabledState.IconRightImage = null;
            this.modifierbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.modifierbtn.onHoverState.BorderRadius = 1;
            this.modifierbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.onHoverState.BorderThickness = 1;
            this.modifierbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.modifierbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.modifierbtn.onHoverState.IconLeftImage = null;
            this.modifierbtn.onHoverState.IconRightImage = null;
            this.modifierbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.modifierbtn.OnIdleState.BorderRadius = 1;
            this.modifierbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.OnIdleState.BorderThickness = 1;
            this.modifierbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(79)))), ((int)(((byte)(160)))));
            this.modifierbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.modifierbtn.OnIdleState.IconLeftImage = null;
            this.modifierbtn.OnIdleState.IconRightImage = null;
            this.modifierbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.modifierbtn.OnPressedState.BorderRadius = 1;
            this.modifierbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.OnPressedState.BorderThickness = 1;
            this.modifierbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.modifierbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.modifierbtn.OnPressedState.IconLeftImage = null;
            this.modifierbtn.OnPressedState.IconRightImage = null;
            this.modifierbtn.Size = new System.Drawing.Size(210, 60);
            this.modifierbtn.TabIndex = 10;
            this.modifierbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.modifierbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.modifierbtn.TextMarginLeft = 0;
            this.modifierbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.modifierbtn.UseDefaultRadiusAndThickness = true;
            this.modifierbtn.Click += new System.EventHandler(this.modifierbtn_Click);
            // 
            // viderbtn
            // 
            this.viderbtn.AllowAnimations = true;
            this.viderbtn.AllowMouseEffects = true;
            this.viderbtn.AllowToggling = false;
            this.viderbtn.AnimationSpeed = 200;
            this.viderbtn.AutoGenerateColors = false;
            this.viderbtn.AutoRoundBorders = false;
            this.viderbtn.AutoSizeLeftIcon = true;
            this.viderbtn.AutoSizeRightIcon = true;
            this.viderbtn.BackColor = System.Drawing.Color.Transparent;
            this.viderbtn.BackColor1 = System.Drawing.Color.White;
            this.viderbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("viderbtn.BackgroundImage")));
            this.viderbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.ButtonText = "Vider";
            this.viderbtn.ButtonTextMarginLeft = 0;
            this.viderbtn.ColorContrastOnClick = 45;
            this.viderbtn.ColorContrastOnHover = 45;
            this.viderbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.viderbtn.CustomizableEdges = borderEdges3;
            this.viderbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.viderbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.viderbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.viderbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.viderbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.viderbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.viderbtn.ForeColor = System.Drawing.Color.Black;
            this.viderbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.viderbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.viderbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.viderbtn.IconMarginLeft = 11;
            this.viderbtn.IconPadding = 10;
            this.viderbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.viderbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.viderbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.viderbtn.IconSize = 25;
            this.viderbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.viderbtn.IdleBorderRadius = 1;
            this.viderbtn.IdleBorderThickness = 1;
            this.viderbtn.IdleFillColor = System.Drawing.Color.White;
            this.viderbtn.IdleIconLeftImage = null;
            this.viderbtn.IdleIconRightImage = null;
            this.viderbtn.IndicateFocus = false;
            this.viderbtn.Location = new System.Drawing.Point(582, 833);
            this.viderbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.viderbtn.Name = "viderbtn";
            this.viderbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.viderbtn.OnDisabledState.BorderRadius = 1;
            this.viderbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.OnDisabledState.BorderThickness = 1;
            this.viderbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.viderbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.viderbtn.OnDisabledState.IconLeftImage = null;
            this.viderbtn.OnDisabledState.IconRightImage = null;
            this.viderbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.viderbtn.onHoverState.BorderRadius = 1;
            this.viderbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.onHoverState.BorderThickness = 1;
            this.viderbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.viderbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.viderbtn.onHoverState.IconLeftImage = null;
            this.viderbtn.onHoverState.IconRightImage = null;
            this.viderbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.viderbtn.OnIdleState.BorderRadius = 1;
            this.viderbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.OnIdleState.BorderThickness = 1;
            this.viderbtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.viderbtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.viderbtn.OnIdleState.IconLeftImage = null;
            this.viderbtn.OnIdleState.IconRightImage = null;
            this.viderbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.viderbtn.OnPressedState.BorderRadius = 1;
            this.viderbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.OnPressedState.BorderThickness = 1;
            this.viderbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.viderbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.viderbtn.OnPressedState.IconLeftImage = null;
            this.viderbtn.OnPressedState.IconRightImage = null;
            this.viderbtn.Size = new System.Drawing.Size(210, 60);
            this.viderbtn.TabIndex = 11;
            this.viderbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.viderbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.viderbtn.TextMarginLeft = 0;
            this.viderbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.viderbtn.UseDefaultRadiusAndThickness = true;
            this.viderbtn.Click += new System.EventHandler(this.viderbtn_Click);
            // 
            // cherchbtn
            // 
            this.cherchbtn.AllowAnimations = true;
            this.cherchbtn.AllowMouseEffects = true;
            this.cherchbtn.AllowToggling = false;
            this.cherchbtn.AnimationSpeed = 200;
            this.cherchbtn.AutoGenerateColors = false;
            this.cherchbtn.AutoRoundBorders = false;
            this.cherchbtn.AutoSizeLeftIcon = true;
            this.cherchbtn.AutoSizeRightIcon = true;
            this.cherchbtn.BackColor = System.Drawing.Color.Transparent;
            this.cherchbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(45)))));
            this.cherchbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cherchbtn.BackgroundImage")));
            this.cherchbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.ButtonText = "Recherche";
            this.cherchbtn.ButtonTextMarginLeft = 0;
            this.cherchbtn.ColorContrastOnClick = 45;
            this.cherchbtn.ColorContrastOnHover = 45;
            this.cherchbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.cherchbtn.CustomizableEdges = borderEdges4;
            this.cherchbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.cherchbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cherchbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cherchbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cherchbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.cherchbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.cherchbtn.ForeColor = System.Drawing.Color.White;
            this.cherchbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cherchbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.cherchbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.cherchbtn.IconMarginLeft = 11;
            this.cherchbtn.IconPadding = 10;
            this.cherchbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cherchbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.cherchbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.cherchbtn.IconSize = 25;
            this.cherchbtn.IdleBorderColor = System.Drawing.Color.White;
            this.cherchbtn.IdleBorderRadius = 1;
            this.cherchbtn.IdleBorderThickness = 1;
            this.cherchbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(45)))));
            this.cherchbtn.IdleIconLeftImage = null;
            this.cherchbtn.IdleIconRightImage = null;
            this.cherchbtn.IndicateFocus = false;
            this.cherchbtn.Location = new System.Drawing.Point(318, 833);
            this.cherchbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.cherchbtn.Name = "cherchbtn";
            this.cherchbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cherchbtn.OnDisabledState.BorderRadius = 1;
            this.cherchbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.OnDisabledState.BorderThickness = 1;
            this.cherchbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cherchbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cherchbtn.OnDisabledState.IconLeftImage = null;
            this.cherchbtn.OnDisabledState.IconRightImage = null;
            this.cherchbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.cherchbtn.onHoverState.BorderRadius = 1;
            this.cherchbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.onHoverState.BorderThickness = 1;
            this.cherchbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cherchbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.cherchbtn.onHoverState.IconLeftImage = null;
            this.cherchbtn.onHoverState.IconRightImage = null;
            this.cherchbtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.cherchbtn.OnIdleState.BorderRadius = 1;
            this.cherchbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.OnIdleState.BorderThickness = 1;
            this.cherchbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(45)))));
            this.cherchbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.cherchbtn.OnIdleState.IconLeftImage = null;
            this.cherchbtn.OnIdleState.IconRightImage = null;
            this.cherchbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.cherchbtn.OnPressedState.BorderRadius = 1;
            this.cherchbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.OnPressedState.BorderThickness = 1;
            this.cherchbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cherchbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.cherchbtn.OnPressedState.IconLeftImage = null;
            this.cherchbtn.OnPressedState.IconRightImage = null;
            this.cherchbtn.Size = new System.Drawing.Size(210, 60);
            this.cherchbtn.TabIndex = 12;
            this.cherchbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.cherchbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.cherchbtn.TextMarginLeft = 0;
            this.cherchbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.cherchbtn.UseDefaultRadiusAndThickness = true;
            this.cherchbtn.Click += new System.EventHandler(this.cherchbtn_Click);
            // 
            // CreateEmplyeeForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.AutoScroll = true;
            this.AutoScrollMargin = new System.Drawing.Size(5, 5);
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(50)))), ((int)(((byte)(59)))));
            this.ClientSize = new System.Drawing.Size(1605, 945);
            this.Controls.Add(this.cherchbtn);
            this.Controls.Add(this.modifierbtn);
            this.Controls.Add(this.viderbtn);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.detailstxtbox);
            this.Controls.Add(this.salairetxtbox);
            this.Controls.Add(this.ajouterbtn);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.typecombox);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.emailtxtbox);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.adressetxtbox);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.phonetxtbox);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.nomtxtbox);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.cintxtbox);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.MaximumSize = new System.Drawing.Size(1605, 945);
            this.Name = "CreateEmplyeeForm";
            this.Text = "Ajouter Un Employé";
            this.Load += new System.EventHandler(this.CreateEmplyeeForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ajouterbtn;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox emailtxtbox;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox adressetxtbox;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox phonetxtbox;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox nomtxtbox;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox cintxtbox;
        private System.Windows.Forms.ComboBox typecombox;
        private Bunifu.UI.WinForms.BunifuTextBox salairetxtbox;
        private System.Windows.Forms.Label label9;
        private Bunifu.UI.WinForms.BunifuTextBox detailstxtbox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton modifierbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton viderbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton cherchbtn;
    }
}