namespace Younes_Entreprise
{
    partial class CreateSupplierForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(CreateSupplierForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.label10 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.villetxtb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ajouterbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.detailstxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.emailtxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.adressetxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.phonetxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nomtxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cintxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.modifierbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.viderbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cherchbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label4 = new System.Windows.Forms.Label();
            this.phone2txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.phone3txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.SuspendLayout();
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label10.Location = new System.Drawing.Point(830, 322);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(285, 25);
            this.label10.TabIndex = 94;
            this.label10.Text = "Adresse 2                            :";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 25.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.Gold;
            this.label7.Location = new System.Drawing.Point(483, 21);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(678, 51);
            this.label7.TabIndex = 91;
            this.label7.Text = "Ajouter Un Nouveau Fournisseur";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label8.Location = new System.Drawing.Point(778, 508);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(133, 25);
            this.label8.TabIndex = 90;
            this.label8.Text = "Autre details";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label5.Location = new System.Drawing.Point(830, 390);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(279, 25);
            this.label5.TabIndex = 88;
            this.label5.Text = "Email Du Fournisseur         :";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label6.Location = new System.Drawing.Point(830, 254);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(282, 25);
            this.label6.TabIndex = 86;
            this.label6.Text = "Adresse Du Fournisseur     :";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label3.Location = new System.Drawing.Point(58, 322);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(281, 25);
            this.label3.TabIndex = 84;
            this.label3.Text = "Telephone Du Fournisseur :";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label2.Location = new System.Drawing.Point(58, 252);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(282, 25);
            this.label2.TabIndex = 82;
            this.label2.Text = "Nom Du Fournisseur           :";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label1.Location = new System.Drawing.Point(58, 189);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(283, 25);
            this.label1.TabIndex = 80;
            this.label1.Text = "ID Du Fournisseur               :";
            // 
            // villetxtb
            // 
            this.villetxtb.AcceptsReturn = false;
            this.villetxtb.AcceptsTab = false;
            this.villetxtb.AnimationSpeed = 200;
            this.villetxtb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.villetxtb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.villetxtb.BackColor = System.Drawing.Color.Transparent;
            this.villetxtb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("villetxtb.BackgroundImage")));
            this.villetxtb.BorderColorActive = System.Drawing.Color.Black;
            this.villetxtb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.villetxtb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.villetxtb.BorderColorIdle = System.Drawing.Color.Silver;
            this.villetxtb.BorderRadius = 1;
            this.villetxtb.BorderThickness = 2;
            this.villetxtb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.villetxtb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.villetxtb.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.villetxtb.DefaultText = "";
            this.villetxtb.FillColor = System.Drawing.Color.White;
            this.villetxtb.HideSelection = true;
            this.villetxtb.IconLeft = null;
            this.villetxtb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.villetxtb.IconPadding = 10;
            this.villetxtb.IconRight = null;
            this.villetxtb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.villetxtb.Lines = new string[0];
            this.villetxtb.Location = new System.Drawing.Point(1121, 312);
            this.villetxtb.Margin = new System.Windows.Forms.Padding(0);
            this.villetxtb.MaxLength = 32767;
            this.villetxtb.MinimumSize = new System.Drawing.Size(1, 1);
            this.villetxtb.Modified = false;
            this.villetxtb.Multiline = false;
            this.villetxtb.Name = "villetxtb";
            stateProperties1.BorderColor = System.Drawing.Color.Black;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.villetxtb.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.villetxtb.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.villetxtb.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.villetxtb.OnIdleState = stateProperties4;
            this.villetxtb.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.villetxtb.PasswordChar = '\0';
            this.villetxtb.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.villetxtb.PlaceholderText = "Enter text";
            this.villetxtb.ReadOnly = false;
            this.villetxtb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.villetxtb.SelectedText = "";
            this.villetxtb.SelectionLength = 0;
            this.villetxtb.SelectionStart = 0;
            this.villetxtb.ShortcutsEnabled = true;
            this.villetxtb.Size = new System.Drawing.Size(414, 46);
            this.villetxtb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.villetxtb.TabIndex = 7;
            this.villetxtb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.villetxtb.TextMarginBottom = 0;
            this.villetxtb.TextMarginLeft = 7;
            this.villetxtb.TextMarginTop = 0;
            this.villetxtb.TextPlaceholder = "Enter text";
            this.villetxtb.UseSystemPasswordChar = false;
            this.villetxtb.WordWrap = true;
            // 
            // ajouterbtn
            // 
            this.ajouterbtn.AllowAnimations = true;
            this.ajouterbtn.AllowMouseEffects = true;
            this.ajouterbtn.AllowToggling = false;
            this.ajouterbtn.AnimationSpeed = 200;
            this.ajouterbtn.AutoGenerateColors = false;
            this.ajouterbtn.AutoRoundBorders = false;
            this.ajouterbtn.AutoSizeLeftIcon = true;
            this.ajouterbtn.AutoSizeRightIcon = true;
            this.ajouterbtn.BackColor = System.Drawing.Color.Transparent;
            this.ajouterbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(183)))), ((int)(((byte)(0)))));
            this.ajouterbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ajouterbtn.BackgroundImage")));
            this.ajouterbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.ButtonText = "Ajouter";
            this.ajouterbtn.ButtonTextMarginLeft = 0;
            this.ajouterbtn.ColorContrastOnClick = 45;
            this.ajouterbtn.ColorContrastOnHover = 45;
            this.ajouterbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.ajouterbtn.CustomizableEdges = borderEdges1;
            this.ajouterbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ajouterbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ajouterbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ajouterbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ajouterbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ajouterbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.ajouterbtn.ForeColor = System.Drawing.Color.White;
            this.ajouterbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ajouterbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ajouterbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ajouterbtn.IconMarginLeft = 11;
            this.ajouterbtn.IconPadding = 10;
            this.ajouterbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ajouterbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ajouterbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ajouterbtn.IconSize = 25;
            this.ajouterbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.ajouterbtn.IdleBorderRadius = 1;
            this.ajouterbtn.IdleBorderThickness = 1;
            this.ajouterbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(183)))), ((int)(((byte)(0)))));
            this.ajouterbtn.IdleIconLeftImage = null;
            this.ajouterbtn.IdleIconRightImage = null;
            this.ajouterbtn.IndicateFocus = false;
            this.ajouterbtn.Location = new System.Drawing.Point(1121, 834);
            this.ajouterbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.ajouterbtn.Name = "ajouterbtn";
            this.ajouterbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ajouterbtn.OnDisabledState.BorderRadius = 1;
            this.ajouterbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.OnDisabledState.BorderThickness = 1;
            this.ajouterbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ajouterbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ajouterbtn.OnDisabledState.IconLeftImage = null;
            this.ajouterbtn.OnDisabledState.IconRightImage = null;
            this.ajouterbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.onHoverState.BorderRadius = 1;
            this.ajouterbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.onHoverState.BorderThickness = 1;
            this.ajouterbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.ajouterbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.onHoverState.IconLeftImage = null;
            this.ajouterbtn.onHoverState.IconRightImage = null;
            this.ajouterbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.ajouterbtn.OnIdleState.BorderRadius = 1;
            this.ajouterbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.OnIdleState.BorderThickness = 1;
            this.ajouterbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(183)))), ((int)(((byte)(0)))));
            this.ajouterbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ajouterbtn.OnIdleState.IconLeftImage = null;
            this.ajouterbtn.OnIdleState.IconRightImage = null;
            this.ajouterbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.OnPressedState.BorderRadius = 1;
            this.ajouterbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ajouterbtn.OnPressedState.BorderThickness = 1;
            this.ajouterbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.ajouterbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.ajouterbtn.OnPressedState.IconLeftImage = null;
            this.ajouterbtn.OnPressedState.IconRightImage = null;
            this.ajouterbtn.Size = new System.Drawing.Size(210, 60);
            this.ajouterbtn.TabIndex = 10;
            this.ajouterbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ajouterbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ajouterbtn.TextMarginLeft = 0;
            this.ajouterbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.ajouterbtn.UseDefaultRadiusAndThickness = true;
            this.ajouterbtn.Click += new System.EventHandler(this.ajouterbtn_Click);
            // 
            // detailstxtbox
            // 
            this.detailstxtbox.AcceptsReturn = false;
            this.detailstxtbox.AcceptsTab = false;
            this.detailstxtbox.AnimationSpeed = 200;
            this.detailstxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.detailstxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.detailstxtbox.BackColor = System.Drawing.Color.Transparent;
            this.detailstxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("detailstxtbox.BackgroundImage")));
            this.detailstxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.detailstxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.detailstxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.detailstxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.detailstxtbox.BorderRadius = 1;
            this.detailstxtbox.BorderThickness = 2;
            this.detailstxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.detailstxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.detailstxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.detailstxtbox.DefaultText = "";
            this.detailstxtbox.FillColor = System.Drawing.Color.White;
            this.detailstxtbox.HideSelection = true;
            this.detailstxtbox.IconLeft = null;
            this.detailstxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.detailstxtbox.IconPadding = 0;
            this.detailstxtbox.IconRight = null;
            this.detailstxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.detailstxtbox.Lines = new string[0];
            this.detailstxtbox.Location = new System.Drawing.Point(472, 545);
            this.detailstxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.detailstxtbox.MaxLength = 32767;
            this.detailstxtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.detailstxtbox.Modified = false;
            this.detailstxtbox.Multiline = true;
            this.detailstxtbox.Name = "detailstxtbox";
            stateProperties5.BorderColor = System.Drawing.Color.Black;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.detailstxtbox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.detailstxtbox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.detailstxtbox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.detailstxtbox.OnIdleState = stateProperties8;
            this.detailstxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 0, 2);
            this.detailstxtbox.PasswordChar = '\0';
            this.detailstxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.detailstxtbox.PlaceholderText = "Enter ICE\r\nRC\r\nPatente\r\nIF\r\nCNSS";
            this.detailstxtbox.ReadOnly = false;
            this.detailstxtbox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.detailstxtbox.SelectedText = "";
            this.detailstxtbox.SelectionLength = 0;
            this.detailstxtbox.SelectionStart = 0;
            this.detailstxtbox.ShortcutsEnabled = true;
            this.detailstxtbox.Size = new System.Drawing.Size(761, 197);
            this.detailstxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.detailstxtbox.TabIndex = 8;
            this.detailstxtbox.TabStop = false;
            this.detailstxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.detailstxtbox.TextMarginBottom = 0;
            this.detailstxtbox.TextMarginLeft = 4;
            this.detailstxtbox.TextMarginTop = 0;
            this.detailstxtbox.TextPlaceholder = "Enter ICE\r\nRC\r\nPatente\r\nIF\r\nCNSS";
            this.detailstxtbox.UseSystemPasswordChar = false;
            this.detailstxtbox.WordWrap = true;
            // 
            // emailtxtbox
            // 
            this.emailtxtbox.AcceptsReturn = false;
            this.emailtxtbox.AcceptsTab = false;
            this.emailtxtbox.AnimationSpeed = 200;
            this.emailtxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailtxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailtxtbox.BackColor = System.Drawing.Color.Transparent;
            this.emailtxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailtxtbox.BackgroundImage")));
            this.emailtxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.emailtxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.emailtxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.emailtxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.emailtxtbox.BorderRadius = 1;
            this.emailtxtbox.BorderThickness = 2;
            this.emailtxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailtxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailtxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.emailtxtbox.DefaultText = "";
            this.emailtxtbox.FillColor = System.Drawing.Color.White;
            this.emailtxtbox.HideSelection = true;
            this.emailtxtbox.IconLeft = null;
            this.emailtxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailtxtbox.IconPadding = 10;
            this.emailtxtbox.IconRight = null;
            this.emailtxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailtxtbox.Lines = new string[0];
            this.emailtxtbox.Location = new System.Drawing.Point(1121, 379);
            this.emailtxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.emailtxtbox.MaxLength = 32767;
            this.emailtxtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailtxtbox.Modified = false;
            this.emailtxtbox.Multiline = false;
            this.emailtxtbox.Name = "emailtxtbox";
            stateProperties9.BorderColor = System.Drawing.Color.Black;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailtxtbox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailtxtbox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailtxtbox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailtxtbox.OnIdleState = stateProperties12;
            this.emailtxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.emailtxtbox.PasswordChar = '\0';
            this.emailtxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.emailtxtbox.PlaceholderText = "Enter text";
            this.emailtxtbox.ReadOnly = false;
            this.emailtxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailtxtbox.SelectedText = "";
            this.emailtxtbox.SelectionLength = 0;
            this.emailtxtbox.SelectionStart = 0;
            this.emailtxtbox.ShortcutsEnabled = true;
            this.emailtxtbox.Size = new System.Drawing.Size(414, 46);
            this.emailtxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailtxtbox.TabIndex = 8;
            this.emailtxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.emailtxtbox.TextMarginBottom = 0;
            this.emailtxtbox.TextMarginLeft = 7;
            this.emailtxtbox.TextMarginTop = 0;
            this.emailtxtbox.TextPlaceholder = "Enter text";
            this.emailtxtbox.UseSystemPasswordChar = false;
            this.emailtxtbox.WordWrap = true;
            // 
            // adressetxtbox
            // 
            this.adressetxtbox.AcceptsReturn = false;
            this.adressetxtbox.AcceptsTab = false;
            this.adressetxtbox.AnimationSpeed = 200;
            this.adressetxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.adressetxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.adressetxtbox.BackColor = System.Drawing.Color.Transparent;
            this.adressetxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("adressetxtbox.BackgroundImage")));
            this.adressetxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.adressetxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.adressetxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.adressetxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.adressetxtbox.BorderRadius = 1;
            this.adressetxtbox.BorderThickness = 2;
            this.adressetxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.adressetxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.adressetxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.adressetxtbox.DefaultText = "";
            this.adressetxtbox.FillColor = System.Drawing.Color.White;
            this.adressetxtbox.HideSelection = true;
            this.adressetxtbox.IconLeft = null;
            this.adressetxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.adressetxtbox.IconPadding = 10;
            this.adressetxtbox.IconRight = null;
            this.adressetxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.adressetxtbox.Lines = new string[0];
            this.adressetxtbox.Location = new System.Drawing.Point(1121, 242);
            this.adressetxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.adressetxtbox.MaxLength = 32767;
            this.adressetxtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.adressetxtbox.Modified = false;
            this.adressetxtbox.Multiline = false;
            this.adressetxtbox.Name = "adressetxtbox";
            stateProperties13.BorderColor = System.Drawing.Color.Black;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adressetxtbox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.adressetxtbox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adressetxtbox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.adressetxtbox.OnIdleState = stateProperties16;
            this.adressetxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.adressetxtbox.PasswordChar = '\0';
            this.adressetxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.adressetxtbox.PlaceholderText = "Enter text";
            this.adressetxtbox.ReadOnly = false;
            this.adressetxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.adressetxtbox.SelectedText = "";
            this.adressetxtbox.SelectionLength = 0;
            this.adressetxtbox.SelectionStart = 0;
            this.adressetxtbox.ShortcutsEnabled = true;
            this.adressetxtbox.Size = new System.Drawing.Size(414, 46);
            this.adressetxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.adressetxtbox.TabIndex = 6;
            this.adressetxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.adressetxtbox.TextMarginBottom = 0;
            this.adressetxtbox.TextMarginLeft = 7;
            this.adressetxtbox.TextMarginTop = 0;
            this.adressetxtbox.TextPlaceholder = "Enter text";
            this.adressetxtbox.UseSystemPasswordChar = false;
            this.adressetxtbox.WordWrap = true;
            // 
            // phonetxtbox
            // 
            this.phonetxtbox.AcceptsReturn = false;
            this.phonetxtbox.AcceptsTab = false;
            this.phonetxtbox.AnimationSpeed = 200;
            this.phonetxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phonetxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phonetxtbox.BackColor = System.Drawing.Color.Transparent;
            this.phonetxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phonetxtbox.BackgroundImage")));
            this.phonetxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.phonetxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phonetxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.phonetxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.phonetxtbox.BorderRadius = 1;
            this.phonetxtbox.BorderThickness = 2;
            this.phonetxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phonetxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phonetxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.phonetxtbox.DefaultText = "";
            this.phonetxtbox.FillColor = System.Drawing.Color.White;
            this.phonetxtbox.HideSelection = true;
            this.phonetxtbox.IconLeft = null;
            this.phonetxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonetxtbox.IconPadding = 10;
            this.phonetxtbox.IconRight = null;
            this.phonetxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phonetxtbox.Lines = new string[0];
            this.phonetxtbox.Location = new System.Drawing.Point(355, 306);
            this.phonetxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.phonetxtbox.MaxLength = 32767;
            this.phonetxtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.phonetxtbox.Modified = false;
            this.phonetxtbox.Multiline = false;
            this.phonetxtbox.Name = "phonetxtbox";
            stateProperties17.BorderColor = System.Drawing.Color.Black;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonetxtbox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phonetxtbox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonetxtbox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phonetxtbox.OnIdleState = stateProperties20;
            this.phonetxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.phonetxtbox.PasswordChar = '\0';
            this.phonetxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.phonetxtbox.PlaceholderText = "Enter text";
            this.phonetxtbox.ReadOnly = false;
            this.phonetxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phonetxtbox.SelectedText = "";
            this.phonetxtbox.SelectionLength = 0;
            this.phonetxtbox.SelectionStart = 0;
            this.phonetxtbox.ShortcutsEnabled = true;
            this.phonetxtbox.Size = new System.Drawing.Size(414, 46);
            this.phonetxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phonetxtbox.TabIndex = 3;
            this.phonetxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phonetxtbox.TextMarginBottom = 0;
            this.phonetxtbox.TextMarginLeft = 7;
            this.phonetxtbox.TextMarginTop = 0;
            this.phonetxtbox.TextPlaceholder = "Enter text";
            this.phonetxtbox.UseSystemPasswordChar = false;
            this.phonetxtbox.WordWrap = true;
            // 
            // nomtxtbox
            // 
            this.nomtxtbox.AcceptsReturn = false;
            this.nomtxtbox.AcceptsTab = false;
            this.nomtxtbox.AnimationSpeed = 200;
            this.nomtxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nomtxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nomtxtbox.BackColor = System.Drawing.Color.Transparent;
            this.nomtxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nomtxtbox.BackgroundImage")));
            this.nomtxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.nomtxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nomtxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.nomtxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.nomtxtbox.BorderRadius = 1;
            this.nomtxtbox.BorderThickness = 2;
            this.nomtxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nomtxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nomtxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.nomtxtbox.DefaultText = "";
            this.nomtxtbox.FillColor = System.Drawing.Color.White;
            this.nomtxtbox.HideSelection = true;
            this.nomtxtbox.IconLeft = null;
            this.nomtxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomtxtbox.IconPadding = 10;
            this.nomtxtbox.IconRight = null;
            this.nomtxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomtxtbox.Lines = new string[0];
            this.nomtxtbox.Location = new System.Drawing.Point(355, 242);
            this.nomtxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.nomtxtbox.MaxLength = 32767;
            this.nomtxtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.nomtxtbox.Modified = false;
            this.nomtxtbox.Multiline = false;
            this.nomtxtbox.Name = "nomtxtbox";
            stateProperties21.BorderColor = System.Drawing.Color.Black;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomtxtbox.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nomtxtbox.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomtxtbox.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomtxtbox.OnIdleState = stateProperties24;
            this.nomtxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.nomtxtbox.PasswordChar = '\0';
            this.nomtxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.nomtxtbox.PlaceholderText = "Enter text";
            this.nomtxtbox.ReadOnly = false;
            this.nomtxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nomtxtbox.SelectedText = "";
            this.nomtxtbox.SelectionLength = 0;
            this.nomtxtbox.SelectionStart = 0;
            this.nomtxtbox.ShortcutsEnabled = true;
            this.nomtxtbox.Size = new System.Drawing.Size(414, 46);
            this.nomtxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nomtxtbox.TabIndex = 2;
            this.nomtxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nomtxtbox.TextMarginBottom = 0;
            this.nomtxtbox.TextMarginLeft = 7;
            this.nomtxtbox.TextMarginTop = 0;
            this.nomtxtbox.TextPlaceholder = "Enter text";
            this.nomtxtbox.UseSystemPasswordChar = false;
            this.nomtxtbox.WordWrap = true;
            // 
            // cintxtbox
            // 
            this.cintxtbox.AcceptsReturn = false;
            this.cintxtbox.AcceptsTab = false;
            this.cintxtbox.AnimationSpeed = 200;
            this.cintxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cintxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cintxtbox.BackColor = System.Drawing.Color.Transparent;
            this.cintxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cintxtbox.BackgroundImage")));
            this.cintxtbox.BorderColorActive = System.Drawing.Color.Black;
            this.cintxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cintxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cintxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.cintxtbox.BorderRadius = 1;
            this.cintxtbox.BorderThickness = 2;
            this.cintxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cintxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cintxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cintxtbox.DefaultText = "";
            this.cintxtbox.FillColor = System.Drawing.Color.White;
            this.cintxtbox.HideSelection = true;
            this.cintxtbox.IconLeft = null;
            this.cintxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cintxtbox.IconPadding = 10;
            this.cintxtbox.IconRight = null;
            this.cintxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cintxtbox.Lines = new string[0];
            this.cintxtbox.Location = new System.Drawing.Point(355, 178);
            this.cintxtbox.Margin = new System.Windows.Forms.Padding(0);
            this.cintxtbox.MaxLength = 32767;
            this.cintxtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.cintxtbox.Modified = false;
            this.cintxtbox.Multiline = false;
            this.cintxtbox.Name = "cintxtbox";
            stateProperties25.BorderColor = System.Drawing.Color.Black;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cintxtbox.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cintxtbox.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cintxtbox.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cintxtbox.OnIdleState = stateProperties28;
            this.cintxtbox.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.cintxtbox.PasswordChar = '\0';
            this.cintxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.cintxtbox.PlaceholderText = "Enter text";
            this.cintxtbox.ReadOnly = false;
            this.cintxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cintxtbox.SelectedText = "";
            this.cintxtbox.SelectionLength = 0;
            this.cintxtbox.SelectionStart = 0;
            this.cintxtbox.ShortcutsEnabled = true;
            this.cintxtbox.Size = new System.Drawing.Size(414, 46);
            this.cintxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cintxtbox.TabIndex = 1;
            this.cintxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cintxtbox.TextMarginBottom = 0;
            this.cintxtbox.TextMarginLeft = 7;
            this.cintxtbox.TextMarginTop = 0;
            this.cintxtbox.TextPlaceholder = "Enter text";
            this.cintxtbox.UseSystemPasswordChar = false;
            this.cintxtbox.WordWrap = true;
            // 
            // modifierbtn
            // 
            this.modifierbtn.AllowAnimations = true;
            this.modifierbtn.AllowMouseEffects = true;
            this.modifierbtn.AllowToggling = false;
            this.modifierbtn.AnimationSpeed = 200;
            this.modifierbtn.AutoGenerateColors = false;
            this.modifierbtn.AutoRoundBorders = false;
            this.modifierbtn.AutoSizeLeftIcon = true;
            this.modifierbtn.AutoSizeRightIcon = true;
            this.modifierbtn.BackColor = System.Drawing.Color.Transparent;
            this.modifierbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(79)))), ((int)(((byte)(160)))));
            this.modifierbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("modifierbtn.BackgroundImage")));
            this.modifierbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.ButtonText = "Modifier";
            this.modifierbtn.ButtonTextMarginLeft = 0;
            this.modifierbtn.ColorContrastOnClick = 45;
            this.modifierbtn.ColorContrastOnHover = 45;
            this.modifierbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.modifierbtn.CustomizableEdges = borderEdges2;
            this.modifierbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.modifierbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modifierbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modifierbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modifierbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.modifierbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.modifierbtn.ForeColor = System.Drawing.Color.White;
            this.modifierbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.modifierbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.modifierbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.modifierbtn.IconMarginLeft = 11;
            this.modifierbtn.IconPadding = 10;
            this.modifierbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.modifierbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.modifierbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.modifierbtn.IconSize = 25;
            this.modifierbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.modifierbtn.IdleBorderRadius = 1;
            this.modifierbtn.IdleBorderThickness = 1;
            this.modifierbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(79)))), ((int)(((byte)(160)))));
            this.modifierbtn.IdleIconLeftImage = null;
            this.modifierbtn.IdleIconRightImage = null;
            this.modifierbtn.IndicateFocus = false;
            this.modifierbtn.Location = new System.Drawing.Point(857, 834);
            this.modifierbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.modifierbtn.Name = "modifierbtn";
            this.modifierbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modifierbtn.OnDisabledState.BorderRadius = 1;
            this.modifierbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.OnDisabledState.BorderThickness = 1;
            this.modifierbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modifierbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modifierbtn.OnDisabledState.IconLeftImage = null;
            this.modifierbtn.OnDisabledState.IconRightImage = null;
            this.modifierbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.modifierbtn.onHoverState.BorderRadius = 1;
            this.modifierbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.onHoverState.BorderThickness = 1;
            this.modifierbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.modifierbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.modifierbtn.onHoverState.IconLeftImage = null;
            this.modifierbtn.onHoverState.IconRightImage = null;
            this.modifierbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.modifierbtn.OnIdleState.BorderRadius = 1;
            this.modifierbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.OnIdleState.BorderThickness = 1;
            this.modifierbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(79)))), ((int)(((byte)(160)))));
            this.modifierbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.modifierbtn.OnIdleState.IconLeftImage = null;
            this.modifierbtn.OnIdleState.IconRightImage = null;
            this.modifierbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.modifierbtn.OnPressedState.BorderRadius = 1;
            this.modifierbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.modifierbtn.OnPressedState.BorderThickness = 1;
            this.modifierbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.modifierbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.modifierbtn.OnPressedState.IconLeftImage = null;
            this.modifierbtn.OnPressedState.IconRightImage = null;
            this.modifierbtn.Size = new System.Drawing.Size(210, 60);
            this.modifierbtn.TabIndex = 11;
            this.modifierbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.modifierbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.modifierbtn.TextMarginLeft = 0;
            this.modifierbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.modifierbtn.UseDefaultRadiusAndThickness = true;
            this.modifierbtn.Click += new System.EventHandler(this.modifierbtn_Click);
            // 
            // viderbtn
            // 
            this.viderbtn.AllowAnimations = true;
            this.viderbtn.AllowMouseEffects = true;
            this.viderbtn.AllowToggling = false;
            this.viderbtn.AnimationSpeed = 200;
            this.viderbtn.AutoGenerateColors = false;
            this.viderbtn.AutoRoundBorders = false;
            this.viderbtn.AutoSizeLeftIcon = true;
            this.viderbtn.AutoSizeRightIcon = true;
            this.viderbtn.BackColor = System.Drawing.Color.Transparent;
            this.viderbtn.BackColor1 = System.Drawing.Color.White;
            this.viderbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("viderbtn.BackgroundImage")));
            this.viderbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.ButtonText = "Vider";
            this.viderbtn.ButtonTextMarginLeft = 0;
            this.viderbtn.ColorContrastOnClick = 45;
            this.viderbtn.ColorContrastOnHover = 45;
            this.viderbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.viderbtn.CustomizableEdges = borderEdges3;
            this.viderbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.viderbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.viderbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.viderbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.viderbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.viderbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.viderbtn.ForeColor = System.Drawing.Color.Black;
            this.viderbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.viderbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.viderbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.viderbtn.IconMarginLeft = 11;
            this.viderbtn.IconPadding = 10;
            this.viderbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.viderbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.viderbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.viderbtn.IconSize = 25;
            this.viderbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.viderbtn.IdleBorderRadius = 1;
            this.viderbtn.IdleBorderThickness = 1;
            this.viderbtn.IdleFillColor = System.Drawing.Color.White;
            this.viderbtn.IdleIconLeftImage = null;
            this.viderbtn.IdleIconRightImage = null;
            this.viderbtn.IndicateFocus = false;
            this.viderbtn.Location = new System.Drawing.Point(593, 834);
            this.viderbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.viderbtn.Name = "viderbtn";
            this.viderbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.viderbtn.OnDisabledState.BorderRadius = 1;
            this.viderbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.OnDisabledState.BorderThickness = 1;
            this.viderbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.viderbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.viderbtn.OnDisabledState.IconLeftImage = null;
            this.viderbtn.OnDisabledState.IconRightImage = null;
            this.viderbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.viderbtn.onHoverState.BorderRadius = 1;
            this.viderbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.onHoverState.BorderThickness = 1;
            this.viderbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.viderbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.viderbtn.onHoverState.IconLeftImage = null;
            this.viderbtn.onHoverState.IconRightImage = null;
            this.viderbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.viderbtn.OnIdleState.BorderRadius = 1;
            this.viderbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.OnIdleState.BorderThickness = 1;
            this.viderbtn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.viderbtn.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.viderbtn.OnIdleState.IconLeftImage = null;
            this.viderbtn.OnIdleState.IconRightImage = null;
            this.viderbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.viderbtn.OnPressedState.BorderRadius = 1;
            this.viderbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.viderbtn.OnPressedState.BorderThickness = 1;
            this.viderbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.viderbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.viderbtn.OnPressedState.IconLeftImage = null;
            this.viderbtn.OnPressedState.IconRightImage = null;
            this.viderbtn.Size = new System.Drawing.Size(210, 60);
            this.viderbtn.TabIndex = 12;
            this.viderbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.viderbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.viderbtn.TextMarginLeft = 0;
            this.viderbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.viderbtn.UseDefaultRadiusAndThickness = true;
            this.viderbtn.Click += new System.EventHandler(this.viderbtn_Click);
            // 
            // cherchbtn
            // 
            this.cherchbtn.AllowAnimations = true;
            this.cherchbtn.AllowMouseEffects = true;
            this.cherchbtn.AllowToggling = false;
            this.cherchbtn.AnimationSpeed = 200;
            this.cherchbtn.AutoGenerateColors = false;
            this.cherchbtn.AutoRoundBorders = false;
            this.cherchbtn.AutoSizeLeftIcon = true;
            this.cherchbtn.AutoSizeRightIcon = true;
            this.cherchbtn.BackColor = System.Drawing.Color.Transparent;
            this.cherchbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(45)))));
            this.cherchbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cherchbtn.BackgroundImage")));
            this.cherchbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.ButtonText = "Recherche";
            this.cherchbtn.ButtonTextMarginLeft = 0;
            this.cherchbtn.ColorContrastOnClick = 45;
            this.cherchbtn.ColorContrastOnHover = 45;
            this.cherchbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.cherchbtn.CustomizableEdges = borderEdges4;
            this.cherchbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.cherchbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cherchbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cherchbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cherchbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.cherchbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.cherchbtn.ForeColor = System.Drawing.Color.White;
            this.cherchbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cherchbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.cherchbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.cherchbtn.IconMarginLeft = 11;
            this.cherchbtn.IconPadding = 10;
            this.cherchbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cherchbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.cherchbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.cherchbtn.IconSize = 25;
            this.cherchbtn.IdleBorderColor = System.Drawing.Color.White;
            this.cherchbtn.IdleBorderRadius = 1;
            this.cherchbtn.IdleBorderThickness = 1;
            this.cherchbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(45)))));
            this.cherchbtn.IdleIconLeftImage = null;
            this.cherchbtn.IdleIconRightImage = null;
            this.cherchbtn.IndicateFocus = false;
            this.cherchbtn.Location = new System.Drawing.Point(329, 834);
            this.cherchbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.cherchbtn.Name = "cherchbtn";
            this.cherchbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cherchbtn.OnDisabledState.BorderRadius = 1;
            this.cherchbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.OnDisabledState.BorderThickness = 1;
            this.cherchbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cherchbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cherchbtn.OnDisabledState.IconLeftImage = null;
            this.cherchbtn.OnDisabledState.IconRightImage = null;
            this.cherchbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.cherchbtn.onHoverState.BorderRadius = 1;
            this.cherchbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.onHoverState.BorderThickness = 1;
            this.cherchbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cherchbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.cherchbtn.onHoverState.IconLeftImage = null;
            this.cherchbtn.onHoverState.IconRightImage = null;
            this.cherchbtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.cherchbtn.OnIdleState.BorderRadius = 1;
            this.cherchbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.OnIdleState.BorderThickness = 1;
            this.cherchbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(37)))), ((int)(((byte)(45)))));
            this.cherchbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.cherchbtn.OnIdleState.IconLeftImage = null;
            this.cherchbtn.OnIdleState.IconRightImage = null;
            this.cherchbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.cherchbtn.OnPressedState.BorderRadius = 1;
            this.cherchbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchbtn.OnPressedState.BorderThickness = 1;
            this.cherchbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cherchbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.cherchbtn.OnPressedState.IconLeftImage = null;
            this.cherchbtn.OnPressedState.IconRightImage = null;
            this.cherchbtn.Size = new System.Drawing.Size(210, 60);
            this.cherchbtn.TabIndex = 13;
            this.cherchbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.cherchbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.cherchbtn.TextMarginLeft = 0;
            this.cherchbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.cherchbtn.UseDefaultRadiusAndThickness = true;
            this.cherchbtn.Click += new System.EventHandler(this.cherchbtn_Click);
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label4.Location = new System.Drawing.Point(58, 392);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(284, 25);
            this.label4.TabIndex = 96;
            this.label4.Text = "Telephone 2                        :";
            // 
            // phone2txt
            // 
            this.phone2txt.AcceptsReturn = false;
            this.phone2txt.AcceptsTab = false;
            this.phone2txt.AnimationSpeed = 200;
            this.phone2txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phone2txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phone2txt.BackColor = System.Drawing.Color.Transparent;
            this.phone2txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phone2txt.BackgroundImage")));
            this.phone2txt.BorderColorActive = System.Drawing.Color.Black;
            this.phone2txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phone2txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.phone2txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.phone2txt.BorderRadius = 1;
            this.phone2txt.BorderThickness = 2;
            this.phone2txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phone2txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phone2txt.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.phone2txt.DefaultText = "";
            this.phone2txt.FillColor = System.Drawing.Color.White;
            this.phone2txt.HideSelection = true;
            this.phone2txt.IconLeft = null;
            this.phone2txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phone2txt.IconPadding = 10;
            this.phone2txt.IconRight = null;
            this.phone2txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phone2txt.Lines = new string[0];
            this.phone2txt.Location = new System.Drawing.Point(355, 379);
            this.phone2txt.Margin = new System.Windows.Forms.Padding(0);
            this.phone2txt.MaxLength = 32767;
            this.phone2txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.phone2txt.Modified = false;
            this.phone2txt.Multiline = false;
            this.phone2txt.Name = "phone2txt";
            stateProperties29.BorderColor = System.Drawing.Color.Black;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phone2txt.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phone2txt.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phone2txt.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phone2txt.OnIdleState = stateProperties32;
            this.phone2txt.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.phone2txt.PasswordChar = '\0';
            this.phone2txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.phone2txt.PlaceholderText = "Enter text";
            this.phone2txt.ReadOnly = false;
            this.phone2txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phone2txt.SelectedText = "";
            this.phone2txt.SelectionLength = 0;
            this.phone2txt.SelectionStart = 0;
            this.phone2txt.ShortcutsEnabled = true;
            this.phone2txt.Size = new System.Drawing.Size(414, 46);
            this.phone2txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phone2txt.TabIndex = 4;
            this.phone2txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phone2txt.TextMarginBottom = 0;
            this.phone2txt.TextMarginLeft = 7;
            this.phone2txt.TextMarginTop = 0;
            this.phone2txt.TextPlaceholder = "Enter text";
            this.phone2txt.UseSystemPasswordChar = false;
            this.phone2txt.WordWrap = true;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label9.Location = new System.Drawing.Point(828, 189);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(284, 25);
            this.label9.TabIndex = 98;
            this.label9.Text = "Telephone 3                        :";
            // 
            // phone3txt
            // 
            this.phone3txt.AcceptsReturn = false;
            this.phone3txt.AcceptsTab = false;
            this.phone3txt.AnimationSpeed = 200;
            this.phone3txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phone3txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phone3txt.BackColor = System.Drawing.Color.Transparent;
            this.phone3txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phone3txt.BackgroundImage")));
            this.phone3txt.BorderColorActive = System.Drawing.Color.Black;
            this.phone3txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phone3txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.phone3txt.BorderColorIdle = System.Drawing.Color.Silver;
            this.phone3txt.BorderRadius = 1;
            this.phone3txt.BorderThickness = 2;
            this.phone3txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phone3txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phone3txt.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.phone3txt.DefaultText = "";
            this.phone3txt.FillColor = System.Drawing.Color.White;
            this.phone3txt.HideSelection = true;
            this.phone3txt.IconLeft = null;
            this.phone3txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phone3txt.IconPadding = 10;
            this.phone3txt.IconRight = null;
            this.phone3txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phone3txt.Lines = new string[0];
            this.phone3txt.Location = new System.Drawing.Point(1121, 178);
            this.phone3txt.Margin = new System.Windows.Forms.Padding(0);
            this.phone3txt.MaxLength = 32767;
            this.phone3txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.phone3txt.Modified = false;
            this.phone3txt.Multiline = false;
            this.phone3txt.Name = "phone3txt";
            stateProperties33.BorderColor = System.Drawing.Color.Black;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phone3txt.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phone3txt.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phone3txt.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phone3txt.OnIdleState = stateProperties36;
            this.phone3txt.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.phone3txt.PasswordChar = '\0';
            this.phone3txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.phone3txt.PlaceholderText = "Enter text";
            this.phone3txt.ReadOnly = false;
            this.phone3txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phone3txt.SelectedText = "";
            this.phone3txt.SelectionLength = 0;
            this.phone3txt.SelectionStart = 0;
            this.phone3txt.ShortcutsEnabled = true;
            this.phone3txt.Size = new System.Drawing.Size(414, 46);
            this.phone3txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phone3txt.TabIndex = 5;
            this.phone3txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phone3txt.TextMarginBottom = 0;
            this.phone3txt.TextMarginLeft = 7;
            this.phone3txt.TextMarginTop = 0;
            this.phone3txt.TextPlaceholder = "Enter text";
            this.phone3txt.UseSystemPasswordChar = false;
            this.phone3txt.WordWrap = true;
            // 
            // CreateSupplierForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.AutoScroll = true;
            this.AutoScrollMargin = new System.Drawing.Size(5, 5);
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(50)))), ((int)(((byte)(59)))));
            this.ClientSize = new System.Drawing.Size(1605, 945);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.phone3txt);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.phone2txt);
            this.Controls.Add(this.cherchbtn);
            this.Controls.Add(this.modifierbtn);
            this.Controls.Add(this.viderbtn);
            this.Controls.Add(this.villetxtb);
            this.Controls.Add(this.ajouterbtn);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.detailstxtbox);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.emailtxtbox);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.adressetxtbox);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.phonetxtbox);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.nomtxtbox);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.cintxtbox);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.MaximumSize = new System.Drawing.Size(1605, 945);
            this.Name = "CreateSupplierForm";
            this.Text = "Ajouter Un Fournisseur";
            this.Load += new System.EventHandler(this.CreateSupplierForm_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox villetxtb;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ajouterbtn;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuTextBox detailstxtbox;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox emailtxtbox;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox adressetxtbox;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox phonetxtbox;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox nomtxtbox;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox cintxtbox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton modifierbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton viderbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton cherchbtn;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox phone2txt;
        private System.Windows.Forms.Label label9;
        private Bunifu.UI.WinForms.BunifuTextBox phone3txt;
    }
}