namespace Younes_Entreprise
{
    partial class OrdersGridviewForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(OrdersGridviewForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.label7 = new System.Windows.Forms.Label();
            this.supprimerbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cherchetxtb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cmdgrid = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.Cmd_id = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.dateTimePicker2 = new System.Windows.Forms.DateTimePicker();
            this.dateTimePicker1 = new System.Windows.Forms.DateTimePicker();
            this.cherchebtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.printblbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.printbcbtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.printfabtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.cmdgrid)).BeginInit();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 25.8F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.Gold;
            this.label7.Location = new System.Drawing.Point(634, 9);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(426, 51);
            this.label7.TabIndex = 65;
            this.label7.Text = "La Liste Des Ventes";
            // 
            // supprimerbtn
            // 
            this.supprimerbtn.AllowAnimations = true;
            this.supprimerbtn.AllowMouseEffects = true;
            this.supprimerbtn.AllowToggling = false;
            this.supprimerbtn.AnimationSpeed = 200;
            this.supprimerbtn.AutoGenerateColors = false;
            this.supprimerbtn.AutoRoundBorders = false;
            this.supprimerbtn.AutoSizeLeftIcon = true;
            this.supprimerbtn.AutoSizeRightIcon = true;
            this.supprimerbtn.BackColor = System.Drawing.Color.Transparent;
            this.supprimerbtn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(20)))), ((int)(((byte)(0)))));
            this.supprimerbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("supprimerbtn.BackgroundImage")));
            this.supprimerbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.supprimerbtn.ButtonText = "Supprimer";
            this.supprimerbtn.ButtonTextMarginLeft = 0;
            this.supprimerbtn.ColorContrastOnClick = 45;
            this.supprimerbtn.ColorContrastOnHover = 45;
            this.supprimerbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.supprimerbtn.CustomizableEdges = borderEdges1;
            this.supprimerbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.supprimerbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.supprimerbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.supprimerbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.supprimerbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.supprimerbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.supprimerbtn.ForeColor = System.Drawing.Color.White;
            this.supprimerbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.supprimerbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.supprimerbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.supprimerbtn.IconMarginLeft = 11;
            this.supprimerbtn.IconPadding = 10;
            this.supprimerbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.supprimerbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.supprimerbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.supprimerbtn.IconSize = 25;
            this.supprimerbtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.supprimerbtn.IdleBorderRadius = 1;
            this.supprimerbtn.IdleBorderThickness = 1;
            this.supprimerbtn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(20)))), ((int)(((byte)(0)))));
            this.supprimerbtn.IdleIconLeftImage = null;
            this.supprimerbtn.IdleIconRightImage = null;
            this.supprimerbtn.IndicateFocus = false;
            this.supprimerbtn.Location = new System.Drawing.Point(309, 23);
            this.supprimerbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.supprimerbtn.Name = "supprimerbtn";
            this.supprimerbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.supprimerbtn.OnDisabledState.BorderRadius = 1;
            this.supprimerbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.supprimerbtn.OnDisabledState.BorderThickness = 1;
            this.supprimerbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.supprimerbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.supprimerbtn.OnDisabledState.IconLeftImage = null;
            this.supprimerbtn.OnDisabledState.IconRightImage = null;
            this.supprimerbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.supprimerbtn.onHoverState.BorderRadius = 1;
            this.supprimerbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.supprimerbtn.onHoverState.BorderThickness = 1;
            this.supprimerbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.supprimerbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.supprimerbtn.onHoverState.IconLeftImage = null;
            this.supprimerbtn.onHoverState.IconRightImage = null;
            this.supprimerbtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.supprimerbtn.OnIdleState.BorderRadius = 1;
            this.supprimerbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.supprimerbtn.OnIdleState.BorderThickness = 1;
            this.supprimerbtn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(20)))), ((int)(((byte)(0)))));
            this.supprimerbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.supprimerbtn.OnIdleState.IconLeftImage = null;
            this.supprimerbtn.OnIdleState.IconRightImage = null;
            this.supprimerbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.supprimerbtn.OnPressedState.BorderRadius = 1;
            this.supprimerbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.supprimerbtn.OnPressedState.BorderThickness = 1;
            this.supprimerbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.supprimerbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.supprimerbtn.OnPressedState.IconLeftImage = null;
            this.supprimerbtn.OnPressedState.IconRightImage = null;
            this.supprimerbtn.Size = new System.Drawing.Size(156, 56);
            this.supprimerbtn.TabIndex = 69;
            this.supprimerbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.supprimerbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.supprimerbtn.TextMarginLeft = 0;
            this.supprimerbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.supprimerbtn.UseDefaultRadiusAndThickness = true;
            this.supprimerbtn.Visible = false;
            this.supprimerbtn.Click += new System.EventHandler(this.supprimerbtn_Click);
            // 
            // cherchetxtb
            // 
            this.cherchetxtb.AcceptsReturn = false;
            this.cherchetxtb.AcceptsTab = false;
            this.cherchetxtb.AnimationSpeed = 200;
            this.cherchetxtb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cherchetxtb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cherchetxtb.BackColor = System.Drawing.Color.Transparent;
            this.cherchetxtb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cherchetxtb.BackgroundImage")));
            this.cherchetxtb.BorderColorActive = System.Drawing.Color.Black;
            this.cherchetxtb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cherchetxtb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cherchetxtb.BorderColorIdle = System.Drawing.Color.Silver;
            this.cherchetxtb.BorderRadius = 1;
            this.cherchetxtb.BorderThickness = 2;
            this.cherchetxtb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cherchetxtb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cherchetxtb.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cherchetxtb.DefaultText = "";
            this.cherchetxtb.FillColor = System.Drawing.Color.White;
            this.cherchetxtb.ForeColor = System.Drawing.Color.Black;
            this.cherchetxtb.HideSelection = true;
            this.cherchetxtb.IconLeft = null;
            this.cherchetxtb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cherchetxtb.IconPadding = 10;
            this.cherchetxtb.IconRight = null;
            this.cherchetxtb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cherchetxtb.Lines = new string[0];
            this.cherchetxtb.Location = new System.Drawing.Point(34, 83);
            this.cherchetxtb.Margin = new System.Windows.Forms.Padding(0);
            this.cherchetxtb.MaximumSize = new System.Drawing.Size(430, 40);
            this.cherchetxtb.MaxLength = 32767;
            this.cherchetxtb.MinimumSize = new System.Drawing.Size(430, 40);
            this.cherchetxtb.Modified = false;
            this.cherchetxtb.Multiline = false;
            this.cherchetxtb.Name = "cherchetxtb";
            stateProperties1.BorderColor = System.Drawing.Color.Black;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cherchetxtb.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cherchetxtb.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cherchetxtb.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cherchetxtb.OnIdleState = stateProperties4;
            this.cherchetxtb.Padding = new System.Windows.Forms.Padding(4, 2, 4, 2);
            this.cherchetxtb.PasswordChar = '\0';
            this.cherchetxtb.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.cherchetxtb.PlaceholderText = "Par : ID - NomClient";
            this.cherchetxtb.ReadOnly = false;
            this.cherchetxtb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cherchetxtb.SelectedText = "";
            this.cherchetxtb.SelectionLength = 0;
            this.cherchetxtb.SelectionStart = 0;
            this.cherchetxtb.ShortcutsEnabled = true;
            this.cherchetxtb.Size = new System.Drawing.Size(430, 40);
            this.cherchetxtb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cherchetxtb.TabIndex = 67;
            this.cherchetxtb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cherchetxtb.TextMarginBottom = 0;
            this.cherchetxtb.TextMarginLeft = 8;
            this.cherchetxtb.TextMarginTop = 0;
            this.cherchetxtb.TextPlaceholder = "Par : ID - NomClient";
            this.cherchetxtb.UseSystemPasswordChar = false;
            this.cherchetxtb.WordWrap = true;
            this.cherchetxtb.TextChange += new System.EventHandler(this.cherchetxtb_TextChange);
            // 
            // cmdgrid
            // 
            this.cmdgrid.AllowCustomTheming = true;
            this.cmdgrid.AllowUserToAddRows = false;
            this.cmdgrid.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.White;
            this.cmdgrid.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.cmdgrid.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.cmdgrid.BackgroundColor = System.Drawing.Color.White;
            this.cmdgrid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.cmdgrid.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.cmdgrid.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Gold;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.Silver;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.cmdgrid.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.cmdgrid.ColumnHeadersHeight = 40;
            this.cmdgrid.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Cmd_id});
            this.cmdgrid.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            this.cmdgrid.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.cmdgrid.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.White;
            this.cmdgrid.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.cmdgrid.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            this.cmdgrid.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.cmdgrid.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.cmdgrid.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Gold;
            this.cmdgrid.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.cmdgrid.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.Black;
            this.cmdgrid.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.Silver;
            this.cmdgrid.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.cmdgrid.CurrentTheme.Name = null;
            this.cmdgrid.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            this.cmdgrid.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.cmdgrid.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.White;
            this.cmdgrid.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.cmdgrid.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.cmdgrid.DefaultCellStyle = dataGridViewCellStyle3;
            this.cmdgrid.EnableHeadersVisualStyles = false;
            this.cmdgrid.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.cmdgrid.HeaderBackColor = System.Drawing.Color.Gold;
            this.cmdgrid.HeaderBgColor = System.Drawing.Color.Empty;
            this.cmdgrid.HeaderForeColor = System.Drawing.Color.Black;
            this.cmdgrid.Location = new System.Drawing.Point(22, 277);
            this.cmdgrid.Margin = new System.Windows.Forms.Padding(0);
            this.cmdgrid.Name = "cmdgrid";
            this.cmdgrid.RowHeadersVisible = false;
            this.cmdgrid.RowHeadersWidth = 51;
            this.cmdgrid.RowTemplate.Height = 40;
            this.cmdgrid.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.cmdgrid.Size = new System.Drawing.Size(1555, 645);
            this.cmdgrid.TabIndex = 70;
            this.cmdgrid.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Dark;
            // 
            // Cmd_id
            // 
            this.Cmd_id.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
            this.Cmd_id.DataPropertyName = "Cmd_id";
            this.Cmd_id.HeaderText = "ID";
            this.Cmd_id.MinimumWidth = 3;
            this.Cmd_id.Name = "Cmd_id";
            this.Cmd_id.Width = 125;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(50)))), ((int)(((byte)(59)))));
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.Gold;
            this.bunifuGroupBox1.BorderRadius = 5;
            this.bunifuGroupBox1.BorderThickness = 3;
            this.bunifuGroupBox1.Controls.Add(this.dateTimePicker2);
            this.bunifuGroupBox1.Controls.Add(this.dateTimePicker1);
            this.bunifuGroupBox1.Controls.Add(this.cherchebtn);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI Black", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.White;
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 30;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(22, 83);
            this.bunifuGroupBox1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuGroupBox1.Size = new System.Drawing.Size(545, 186);
            this.bunifuGroupBox1.TabIndex = 71;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Recherche Par Date :";
            // 
            // dateTimePicker2
            // 
            this.dateTimePicker2.Font = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dateTimePicker2.Location = new System.Drawing.Point(19, 114);
            this.dateTimePicker2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.dateTimePicker2.MaximumSize = new System.Drawing.Size(320, 31);
            this.dateTimePicker2.MinimumSize = new System.Drawing.Size(320, 31);
            this.dateTimePicker2.Name = "dateTimePicker2";
            this.dateTimePicker2.Size = new System.Drawing.Size(320, 31);
            this.dateTimePicker2.TabIndex = 99;
            // 
            // dateTimePicker1
            // 
            this.dateTimePicker1.Font = new System.Drawing.Font("Segoe UI", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dateTimePicker1.Location = new System.Drawing.Point(19, 52);
            this.dateTimePicker1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.dateTimePicker1.MaximumSize = new System.Drawing.Size(320, 31);
            this.dateTimePicker1.MinimumSize = new System.Drawing.Size(320, 31);
            this.dateTimePicker1.Name = "dateTimePicker1";
            this.dateTimePicker1.Size = new System.Drawing.Size(320, 31);
            this.dateTimePicker1.TabIndex = 98;
            // 
            // cherchebtn
            // 
            this.cherchebtn.AllowAnimations = true;
            this.cherchebtn.AllowMouseEffects = true;
            this.cherchebtn.AllowToggling = false;
            this.cherchebtn.AnimationSpeed = 200;
            this.cherchebtn.AutoGenerateColors = false;
            this.cherchebtn.AutoRoundBorders = false;
            this.cherchebtn.AutoSizeLeftIcon = true;
            this.cherchebtn.AutoSizeRightIcon = true;
            this.cherchebtn.BackColor = System.Drawing.Color.Transparent;
            this.cherchebtn.BackColor1 = System.Drawing.SystemColors.WindowFrame;
            this.cherchebtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cherchebtn.BackgroundImage")));
            this.cherchebtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchebtn.ButtonText = "Chercher";
            this.cherchebtn.ButtonTextMarginLeft = 0;
            this.cherchebtn.ColorContrastOnClick = 45;
            this.cherchebtn.ColorContrastOnHover = 45;
            this.cherchebtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.cherchebtn.CustomizableEdges = borderEdges2;
            this.cherchebtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.cherchebtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cherchebtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cherchebtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cherchebtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.cherchebtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.cherchebtn.ForeColor = System.Drawing.Color.White;
            this.cherchebtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.cherchebtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.cherchebtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.cherchebtn.IconMarginLeft = 11;
            this.cherchebtn.IconPadding = 10;
            this.cherchebtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.cherchebtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.cherchebtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.cherchebtn.IconSize = 25;
            this.cherchebtn.IdleBorderColor = System.Drawing.Color.Transparent;
            this.cherchebtn.IdleBorderRadius = 1;
            this.cherchebtn.IdleBorderThickness = 1;
            this.cherchebtn.IdleFillColor = System.Drawing.SystemColors.WindowFrame;
            this.cherchebtn.IdleIconLeftImage = null;
            this.cherchebtn.IdleIconRightImage = null;
            this.cherchebtn.IndicateFocus = false;
            this.cherchebtn.Location = new System.Drawing.Point(360, 67);
            this.cherchebtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.cherchebtn.Name = "cherchebtn";
            this.cherchebtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.cherchebtn.OnDisabledState.BorderRadius = 1;
            this.cherchebtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchebtn.OnDisabledState.BorderThickness = 1;
            this.cherchebtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cherchebtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.cherchebtn.OnDisabledState.IconLeftImage = null;
            this.cherchebtn.OnDisabledState.IconRightImage = null;
            this.cherchebtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.cherchebtn.onHoverState.BorderRadius = 1;
            this.cherchebtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchebtn.onHoverState.BorderThickness = 1;
            this.cherchebtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cherchebtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.cherchebtn.onHoverState.IconLeftImage = null;
            this.cherchebtn.onHoverState.IconRightImage = null;
            this.cherchebtn.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.cherchebtn.OnIdleState.BorderRadius = 1;
            this.cherchebtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchebtn.OnIdleState.BorderThickness = 1;
            this.cherchebtn.OnIdleState.FillColor = System.Drawing.SystemColors.WindowFrame;
            this.cherchebtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.cherchebtn.OnIdleState.IconLeftImage = null;
            this.cherchebtn.OnIdleState.IconRightImage = null;
            this.cherchebtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.cherchebtn.OnPressedState.BorderRadius = 1;
            this.cherchebtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.cherchebtn.OnPressedState.BorderThickness = 1;
            this.cherchebtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.cherchebtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.cherchebtn.OnPressedState.IconLeftImage = null;
            this.cherchebtn.OnPressedState.IconRightImage = null;
            this.cherchebtn.Size = new System.Drawing.Size(156, 56);
            this.cherchebtn.TabIndex = 97;
            this.cherchebtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.cherchebtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.cherchebtn.TextMarginLeft = 0;
            this.cherchebtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.cherchebtn.UseDefaultRadiusAndThickness = true;
            this.cherchebtn.Click += new System.EventHandler(this.cherchebtn_Click);
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(50)))), ((int)(((byte)(59)))));
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.Gold;
            this.bunifuGroupBox2.BorderRadius = 5;
            this.bunifuGroupBox2.BorderThickness = 3;
            this.bunifuGroupBox2.Controls.Add(this.cherchetxtb);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Segoe UI Black", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuGroupBox2.ForeColor = System.Drawing.Color.White;
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 30;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(581, 83);
            this.bunifuGroupBox2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuGroupBox2.Size = new System.Drawing.Size(488, 186);
            this.bunifuGroupBox2.TabIndex = 72;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Recherche Générale :";
            // 
            // printblbtn
            // 
            this.printblbtn.AllowAnimations = true;
            this.printblbtn.AllowMouseEffects = true;
            this.printblbtn.AllowToggling = false;
            this.printblbtn.AnimationSpeed = 200;
            this.printblbtn.AutoGenerateColors = false;
            this.printblbtn.AutoRoundBorders = false;
            this.printblbtn.AutoSizeLeftIcon = true;
            this.printblbtn.AutoSizeRightIcon = true;
            this.printblbtn.BackColor = System.Drawing.Color.Transparent;
            this.printblbtn.BackColor1 = System.Drawing.Color.Black;
            this.printblbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("printblbtn.BackgroundImage")));
            this.printblbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printblbtn.ButtonText = "Bon De Livraison";
            this.printblbtn.ButtonTextMarginLeft = 0;
            this.printblbtn.ColorContrastOnClick = 45;
            this.printblbtn.ColorContrastOnHover = 45;
            this.printblbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.printblbtn.CustomizableEdges = borderEdges3;
            this.printblbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.printblbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.printblbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.printblbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.printblbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.printblbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.printblbtn.ForeColor = System.Drawing.Color.White;
            this.printblbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.printblbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.printblbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.printblbtn.IconMarginLeft = 11;
            this.printblbtn.IconPadding = 10;
            this.printblbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.printblbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.printblbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.printblbtn.IconSize = 25;
            this.printblbtn.IdleBorderColor = System.Drawing.Color.White;
            this.printblbtn.IdleBorderRadius = 1;
            this.printblbtn.IdleBorderThickness = 1;
            this.printblbtn.IdleFillColor = System.Drawing.Color.Black;
            this.printblbtn.IdleIconLeftImage = null;
            this.printblbtn.IdleIconRightImage = null;
            this.printblbtn.IndicateFocus = false;
            this.printblbtn.Location = new System.Drawing.Point(1339, 111);
            this.printblbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.printblbtn.Name = "printblbtn";
            this.printblbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.printblbtn.OnDisabledState.BorderRadius = 1;
            this.printblbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printblbtn.OnDisabledState.BorderThickness = 1;
            this.printblbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.printblbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.printblbtn.OnDisabledState.IconLeftImage = null;
            this.printblbtn.OnDisabledState.IconRightImage = null;
            this.printblbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.printblbtn.onHoverState.BorderRadius = 1;
            this.printblbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printblbtn.onHoverState.BorderThickness = 1;
            this.printblbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.printblbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.printblbtn.onHoverState.IconLeftImage = null;
            this.printblbtn.onHoverState.IconRightImage = null;
            this.printblbtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.printblbtn.OnIdleState.BorderRadius = 1;
            this.printblbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printblbtn.OnIdleState.BorderThickness = 1;
            this.printblbtn.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.printblbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.printblbtn.OnIdleState.IconLeftImage = null;
            this.printblbtn.OnIdleState.IconRightImage = null;
            this.printblbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.printblbtn.OnPressedState.BorderRadius = 1;
            this.printblbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printblbtn.OnPressedState.BorderThickness = 1;
            this.printblbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.printblbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.printblbtn.OnPressedState.IconLeftImage = null;
            this.printblbtn.OnPressedState.IconRightImage = null;
            this.printblbtn.Size = new System.Drawing.Size(238, 60);
            this.printblbtn.TabIndex = 129;
            this.printblbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.printblbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.printblbtn.TextMarginLeft = 0;
            this.printblbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.printblbtn.UseDefaultRadiusAndThickness = true;
            this.printblbtn.Click += new System.EventHandler(this.printblbtn_Click);
            // 
            // printbcbtn
            // 
            this.printbcbtn.AllowAnimations = true;
            this.printbcbtn.AllowMouseEffects = true;
            this.printbcbtn.AllowToggling = false;
            this.printbcbtn.AnimationSpeed = 200;
            this.printbcbtn.AutoGenerateColors = false;
            this.printbcbtn.AutoRoundBorders = false;
            this.printbcbtn.AutoSizeLeftIcon = true;
            this.printbcbtn.AutoSizeRightIcon = true;
            this.printbcbtn.BackColor = System.Drawing.Color.Transparent;
            this.printbcbtn.BackColor1 = System.Drawing.Color.Black;
            this.printbcbtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("printbcbtn.BackgroundImage")));
            this.printbcbtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printbcbtn.ButtonText = "Devis";
            this.printbcbtn.ButtonTextMarginLeft = 0;
            this.printbcbtn.ColorContrastOnClick = 45;
            this.printbcbtn.ColorContrastOnHover = 45;
            this.printbcbtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.printbcbtn.CustomizableEdges = borderEdges4;
            this.printbcbtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.printbcbtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.printbcbtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.printbcbtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.printbcbtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.printbcbtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.printbcbtn.ForeColor = System.Drawing.Color.White;
            this.printbcbtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.printbcbtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.printbcbtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.printbcbtn.IconMarginLeft = 11;
            this.printbcbtn.IconPadding = 10;
            this.printbcbtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.printbcbtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.printbcbtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.printbcbtn.IconSize = 25;
            this.printbcbtn.IdleBorderColor = System.Drawing.Color.White;
            this.printbcbtn.IdleBorderRadius = 1;
            this.printbcbtn.IdleBorderThickness = 1;
            this.printbcbtn.IdleFillColor = System.Drawing.Color.Black;
            this.printbcbtn.IdleIconLeftImage = null;
            this.printbcbtn.IdleIconRightImage = null;
            this.printbcbtn.IndicateFocus = false;
            this.printbcbtn.Location = new System.Drawing.Point(1339, 189);
            this.printbcbtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.printbcbtn.Name = "printbcbtn";
            this.printbcbtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.printbcbtn.OnDisabledState.BorderRadius = 1;
            this.printbcbtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printbcbtn.OnDisabledState.BorderThickness = 1;
            this.printbcbtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.printbcbtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.printbcbtn.OnDisabledState.IconLeftImage = null;
            this.printbcbtn.OnDisabledState.IconRightImage = null;
            this.printbcbtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.printbcbtn.onHoverState.BorderRadius = 1;
            this.printbcbtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printbcbtn.onHoverState.BorderThickness = 1;
            this.printbcbtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.printbcbtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.printbcbtn.onHoverState.IconLeftImage = null;
            this.printbcbtn.onHoverState.IconRightImage = null;
            this.printbcbtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.printbcbtn.OnIdleState.BorderRadius = 1;
            this.printbcbtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printbcbtn.OnIdleState.BorderThickness = 1;
            this.printbcbtn.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.printbcbtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.printbcbtn.OnIdleState.IconLeftImage = null;
            this.printbcbtn.OnIdleState.IconRightImage = null;
            this.printbcbtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.printbcbtn.OnPressedState.BorderRadius = 1;
            this.printbcbtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printbcbtn.OnPressedState.BorderThickness = 1;
            this.printbcbtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.printbcbtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.printbcbtn.OnPressedState.IconLeftImage = null;
            this.printbcbtn.OnPressedState.IconRightImage = null;
            this.printbcbtn.Size = new System.Drawing.Size(238, 60);
            this.printbcbtn.TabIndex = 130;
            this.printbcbtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.printbcbtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.printbcbtn.TextMarginLeft = 0;
            this.printbcbtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.printbcbtn.UseDefaultRadiusAndThickness = true;
            this.printbcbtn.Click += new System.EventHandler(this.printbcbtn_Click);
            // 
            // printfabtn
            // 
            this.printfabtn.AllowAnimations = true;
            this.printfabtn.AllowMouseEffects = true;
            this.printfabtn.AllowToggling = false;
            this.printfabtn.AnimationSpeed = 200;
            this.printfabtn.AutoGenerateColors = false;
            this.printfabtn.AutoRoundBorders = false;
            this.printfabtn.AutoSizeLeftIcon = true;
            this.printfabtn.AutoSizeRightIcon = true;
            this.printfabtn.BackColor = System.Drawing.Color.Transparent;
            this.printfabtn.BackColor1 = System.Drawing.Color.Black;
            this.printfabtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("printfabtn.BackgroundImage")));
            this.printfabtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printfabtn.ButtonText = "Facture";
            this.printfabtn.ButtonTextMarginLeft = 0;
            this.printfabtn.ColorContrastOnClick = 45;
            this.printfabtn.ColorContrastOnHover = 45;
            this.printfabtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.printfabtn.CustomizableEdges = borderEdges5;
            this.printfabtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.printfabtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.printfabtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.printfabtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.printfabtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.printfabtn.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.printfabtn.ForeColor = System.Drawing.Color.White;
            this.printfabtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.printfabtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.printfabtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.printfabtn.IconMarginLeft = 11;
            this.printfabtn.IconPadding = 10;
            this.printfabtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.printfabtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.printfabtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.printfabtn.IconSize = 25;
            this.printfabtn.IdleBorderColor = System.Drawing.Color.White;
            this.printfabtn.IdleBorderRadius = 1;
            this.printfabtn.IdleBorderThickness = 1;
            this.printfabtn.IdleFillColor = System.Drawing.Color.Black;
            this.printfabtn.IdleIconLeftImage = null;
            this.printfabtn.IdleIconRightImage = null;
            this.printfabtn.IndicateFocus = false;
            this.printfabtn.Location = new System.Drawing.Point(1092, 146);
            this.printfabtn.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.printfabtn.Name = "printfabtn";
            this.printfabtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.printfabtn.OnDisabledState.BorderRadius = 1;
            this.printfabtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printfabtn.OnDisabledState.BorderThickness = 1;
            this.printfabtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.printfabtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.printfabtn.OnDisabledState.IconLeftImage = null;
            this.printfabtn.OnDisabledState.IconRightImage = null;
            this.printfabtn.onHoverState.BorderColor = System.Drawing.Color.Yellow;
            this.printfabtn.onHoverState.BorderRadius = 1;
            this.printfabtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printfabtn.onHoverState.BorderThickness = 1;
            this.printfabtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.printfabtn.onHoverState.ForeColor = System.Drawing.Color.Yellow;
            this.printfabtn.onHoverState.IconLeftImage = null;
            this.printfabtn.onHoverState.IconRightImage = null;
            this.printfabtn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.printfabtn.OnIdleState.BorderRadius = 1;
            this.printfabtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printfabtn.OnIdleState.BorderThickness = 1;
            this.printfabtn.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.printfabtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.printfabtn.OnIdleState.IconLeftImage = null;
            this.printfabtn.OnIdleState.IconRightImage = null;
            this.printfabtn.OnPressedState.BorderColor = System.Drawing.Color.Yellow;
            this.printfabtn.OnPressedState.BorderRadius = 1;
            this.printfabtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.printfabtn.OnPressedState.BorderThickness = 1;
            this.printfabtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(61)))), ((int)(((byte)(70)))));
            this.printfabtn.OnPressedState.ForeColor = System.Drawing.Color.Yellow;
            this.printfabtn.OnPressedState.IconLeftImage = null;
            this.printfabtn.OnPressedState.IconRightImage = null;
            this.printfabtn.Size = new System.Drawing.Size(221, 60);
            this.printfabtn.TabIndex = 131;
            this.printfabtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.printfabtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.printfabtn.TextMarginLeft = 0;
            this.printfabtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.printfabtn.UseDefaultRadiusAndThickness = true;
            this.printfabtn.Click += new System.EventHandler(this.printfabtn_Click);
            // 
            // OrdersGridviewForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(120F, 120F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.AutoScroll = true;
            this.AutoScrollMargin = new System.Drawing.Size(5, 5);
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(50)))), ((int)(((byte)(59)))));
            this.ClientSize = new System.Drawing.Size(1605, 945);
            this.Controls.Add(this.printfabtn);
            this.Controls.Add(this.printbcbtn);
            this.Controls.Add(this.printblbtn);
            this.Controls.Add(this.supprimerbtn);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.cmdgrid);
            this.Controls.Add(this.label7);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.MaximumSize = new System.Drawing.Size(1605, 945);
            this.Name = "OrdersGridviewForm";
            this.Text = "Liste Des Ventes";
            this.Load += new System.EventHandler(this.OrdersGridviewForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.cmdgrid)).EndInit();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox2.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton supprimerbtn;
        private Bunifu.UI.WinForms.BunifuTextBox cherchetxtb;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuDataGridView cmdgrid;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton cherchebtn;
        private System.Windows.Forms.DateTimePicker dateTimePicker2;
        private System.Windows.Forms.DateTimePicker dateTimePicker1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton printblbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton printbcbtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton printfabtn;
        private System.Windows.Forms.DataGridViewTextBoxColumn Cmd_id;
    }
}